packages:
  - apps/*
  - packages/*
  - tooling/*
nodeLinker: hoisted
autoInstallPeers: true
strictPeerDependencies: false
preferFrozenLockfile: true
shamefullyHoist: false
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*types*'
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - prisma
  - msw
allowBuilds:
  '@biomejs/biome': set this to true or false
  esbuild: set this to true or false
