[pytest]
# حل مشکل PermissionError در ویندوز با تغییر مسیر basetemp
basetemp = D:/eco_nojin/.pytest_cache/tmp
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -q
