import {
  cppStatusApiV1ModelsCppStatusGet,
  type cppStatusApiV1ModelsCppStatusGetResponse,
  listLandscapesApiV1PlatformLandscapesGet,
  type listLandscapesApiV1PlatformLandscapesGetResponse,
  listModelsApiV1HydromaModelsGet,
  type listModelsApiV1HydromaModelsGetResponse,
  listProductsApiV1MarketplaceProductsGet,
  type listProductsApiV1MarketplaceProductsGetResponse,
  marketplaceStatsApiV1MarketplaceStatsGet,
  type marketplaceStatsApiV1MarketplaceStatsGetResponse,
  platformHealthApiV1PlatformHealthGet,
  type platformHealthApiV1PlatformHealthGetResponse,
  platformStatsApiV1PlatformStatsGet,
  type platformStatsApiV1PlatformStatsGetResponse,

  // AI endpoints
  chatApiV1AiChatPost,
  type ChatRequest,
  type chatApiV1AiChatPostResponse,
  streamChatApiV1AiStreamPost,
  type streamChatApiV1AiStreamPostResponse,
  aiHealthApiV1AiHealthGet,
  type aiHealthApiV1AiHealthGetResponse,
  getHistoryApiV1AiHistoryGet,
  type GetHistoryApiV1AiHistoryGetParams,
  type getHistoryApiV1AiHistoryGetResponse,
  textToSpeechApiV1AiVoiceTtsPost,
  type textToSpeechApiV1AiVoiceTtsPostResponse,
  applyScenarioApiV1ScenariosApplyPost,
  type ScenarioRequest,
  type applyScenarioApiV1ScenariosApplyPostResponse,
  compareScenariosApiV1ScenariosCompareFarmIdGet,
  type compareScenariosApiV1ScenariosCompareFarmIdGetResponse,
  getScenarioImpactApiV1AnalyticsScenarioImpactGet,
  type getScenarioImpactApiV1AnalyticsScenarioImpactGetResponse,
  analyzeLandApiV1PlatformAnalyzePost,
  type AnalyzeRequest,
  type analyzeLandApiV1PlatformAnalyzePostResponse,
  analyzeSoilApiV1SoilAnalyzePost,
  type SoilAnalysisRequest,
  type analyzeSoilApiV1SoilAnalyzePostResponse,
  analyzeSatelliteApiV1SatelliteAnalyzePost,
  type SatelliteAnalyzeRequest,
  type analyzeSatelliteApiV1SatelliteAnalyzePostResponse,
  realLandAnalysisApiV1SatelliteRealLandPost,
  type realLandAnalysisApiV1SatelliteRealLandPostResponse,
  generateAiDraftApiV1AdminContentGenerateDraftPost,
  type GenerateAiDraftApiV1AdminContentGenerateDraftPostParams,
  type generateAiDraftApiV1AdminContentGenerateDraftPostResponse,
  adminAiStatusEndpointApiV1AdminAiStatusGet,
  type adminAiStatusEndpointApiV1AdminAiStatusGetResponse,
  adminAiChatApiV1AdminAiChatPost,
  type AdminAIChatRequest,
  type adminAiChatApiV1AdminAiChatPostResponse,
  ivrStartApiV1VoiceIvrStartPost,
  type IVRStartIn,
  type ivrStartApiV1VoiceIvrStartPostResponse,
  ivrDtmfApiV1VoiceIvrDtmfPost,
  type IVRDTMFIn,
  type ivrDtmfApiV1VoiceIvrDtmfPostResponse,
  ivrMenuPreviewApiV1VoiceIvrMenuLanguageGet,
  type ivrMenuPreviewApiV1VoiceIvrMenuLanguageGetResponse,
  ivrCallApiV1VoiceIvrCallPost,
  type IVRCallIn,
  type ivrCallApiV1VoiceIvrCallPostResponse,
  ivrSmsApiV1VoiceIvrSmsPost,
  type IVRSMSIn,
  type ivrSmsApiV1VoiceIvrSmsPostResponse,
  textToSpeechApiV1VoiceTtsPost,
  type TTSIn,
  type textToSpeechApiV1VoiceTtsPostResponse,
  speechToTextApiV1VoiceSttPost,
  type STTIn,
  type speechToTextApiV1VoiceSttPostResponse,
  voiceAskApiV1VoiceAskPost,
  type AskIn,
  type voiceAskApiV1VoiceAskPostResponse,
  voiceHealthApiV1VoiceHealthGet,
  type voiceHealthApiV1VoiceHealthGetResponse,
  voiceLanguagesApiV1VoiceLanguagesGet,
  type voiceLanguagesApiV1VoiceLanguagesGetResponse,
} from '@eco/api-client';

// Thin namespace over the Orval-generated client (@eco/api-client).
// Every function hits the real API gateway — no mock layer exists.
export const api = {
  platform: {
    health: () => platformHealthApiV1PlatformHealthGet(),
    stats: () => platformStatsApiV1PlatformStatsGet(),
    landscapes: () => listLandscapesApiV1PlatformLandscapesGet(),
  },
  hydroma: {
    models: () => listModelsApiV1HydromaModelsGet(),
    cppStatus: () => cppStatusApiV1ModelsCppStatusGet(),
  },
  marketplace: {
    products: () => listProductsApiV1MarketplaceProductsGet(),
    stats: () => marketplaceStatsApiV1MarketplaceStatsGet(),
  },
  ai: {
    // Chat
    chat: (request: ChatRequest) => chatApiV1AiChatPost(request),
    streamChat: (request: ChatRequest) => streamChatApiV1AiStreamPost(request),
    health: () => aiHealthApiV1AiHealthGet(),
    history: (params?: GetHistoryApiV1AiHistoryGetParams) => getHistoryApiV1AiHistoryGet(params),

    // Voice / TTS (OpenAI-compatible endpoints under /api/v1/ai/voice)
    tts: (request: ChatRequest) => textToSpeechApiV1AiVoiceTtsPost(request),
    voiceAsk: (request: { question: string; language?: 'en' | 'fa' | 'ar' }) => voiceAskApiV1VoiceAskPost(request),
    voiceHealth: () => voiceHealthApiV1VoiceHealthGet(),
    voiceLanguages: () => voiceLanguagesApiV1VoiceLanguagesGet(),

    // Voice (IVR/STT/TTS under /api/v1/voice)
    ttsVoice: (request: { text: string; language?: 'en' | 'fa' | 'ar' }) => textToSpeechApiV1VoiceTtsPost(request),
    sttVoice: (request: { audio_base64: string; language?: 'en' | 'fa' | 'ar' }) => speechToTextApiV1VoiceSttPost(request),

    // Scenarios
    applyScenario: (request: ScenarioRequest) => applyScenarioApiV1ScenariosApplyPost(request),
    compareScenarios: (farmId: number) => compareScenariosApiV1ScenariosCompareFarmIdGet(farmId),
    scenarioImpact: () => getScenarioImpactApiV1AnalyticsScenarioImpactGet(),

    // Analysis
    analyzeLand: (request: AnalyzeRequest) => analyzeLandApiV1PlatformAnalyzePost(request),
    analyzeSoil: (request: SoilAnalysisRequest) => analyzeSoilApiV1SoilAnalyzePost(request),
    analyzeSatellite: (request: SatelliteAnalyzeRequest) => analyzeSatelliteApiV1SatelliteAnalyzePost(request),
    realLandAnalysis: (request: SatelliteAnalyzeRequest) => realLandAnalysisApiV1SatelliteRealLandPost(request),

    // Admin
    adminStatus: () => adminAiStatusEndpointApiV1AdminAiStatusGet(),
    adminChat: (request: { question: string; page?: string }) => adminAiChatApiV1AdminAiChatPost(request),

    // Content generation
    generateDraft: (params: { topic: string; category?: string }) => generateAiDraftApiV1AdminContentGenerateDraftPost(params),

    // IVR
    ivrStart: (request: { session_id: string; phone_number: string; language?: 'en' | 'fa' | 'ar' }) => ivrStartApiV1VoiceIvrStartPost(request),
    ivrDtmf: (request: { session_id: string; digit: string }) => ivrDtmfApiV1VoiceIvrDtmfPost(request),
    ivrMenu: (language: 'en' | 'fa' | 'ar') => ivrMenuPreviewApiV1VoiceIvrMenuLanguageGet(language),
    ivrCall: (request: { phone_number: string; twiml?: string; menu_language?: 'en' | 'fa' | 'ar' }) => ivrCallApiV1VoiceIvrCallPost(request),
    ivrSms: (request: { to: string; body: string }) => ivrSmsApiV1VoiceIvrSmsPost(request),
  },
};

export type {
  cppStatusApiV1ModelsCppStatusGetResponse as CppStatus,
  listLandscapesApiV1PlatformLandscapesGetResponse as Landscapes,
  listModelsApiV1HydromaModelsGetResponse as HydromaModels,
  listProductsApiV1MarketplaceProductsGetResponse as MarketplaceProducts,
  marketplaceStatsApiV1MarketplaceStatsGetResponse as MarketplaceStats,
  platformHealthApiV1PlatformHealthGetResponse as PlatformHealth,
  platformStatsApiV1PlatformStatsGetResponse as PlatformStats,

  // AI types
  ChatRequest,
  chatApiV1AiChatPostResponse as AiChatResponse,
  streamChatApiV1AiStreamPostResponse as AiStreamChatResponse,
  aiHealthApiV1AiHealthGetResponse as AiHealth,
  GetHistoryApiV1AiHistoryGetParams,
  getHistoryApiV1AiHistoryGetResponse as AiHistory,
  textToSpeechApiV1AiVoiceTtsPostResponse as AiTtsResponse,
  applyScenarioApiV1ScenariosApplyPostResponse as ApplyScenarioResponse,
  compareScenariosApiV1ScenariosCompareFarmIdGetResponse as CompareScenariosResponse,
  getScenarioImpactApiV1AnalyticsScenarioImpactGetResponse as ScenarioImpact,
  AnalyzeRequest,
  analyzeLandApiV1PlatformAnalyzePostResponse as AnalyzeLandResponse,
  SoilAnalysisRequest,
  analyzeSoilApiV1SoilAnalyzePostResponse as AnalyzeSoilResponse,
  SatelliteAnalyzeRequest,
  analyzeSatelliteApiV1SatelliteAnalyzePostResponse as AnalyzeSatelliteResponse,
  realLandAnalysisApiV1SatelliteRealLandPostResponse as RealLandAnalysisResponse,
  GenerateAiDraftApiV1AdminContentGenerateDraftPostParams,
  generateAiDraftApiV1AdminContentGenerateDraftPostResponse as GenerateDraftResponse,
  IVRStartIn,
  ivrStartApiV1VoiceIvrStartPostResponse as IVRStartResponse,
  IVRDTMFIn,
  ivrDtmfApiV1VoiceIvrDtmfPostResponse as IVRDTMFResponse,
  ivrMenuPreviewApiV1VoiceIvrMenuLanguageGetResponse as IVRMenuResponse,
  IVRCallIn,
  ivrCallApiV1VoiceIvrCallPostResponse as IVRCallResponse,
  IVRSMSIn,
  ivrSmsApiV1VoiceIvrSmsPostResponse as IVRSMSResponse,
};