import type { ProfileSettings } from './profiletypes';

export const profileSettings: Record<'fa' | 'en', ProfileSettings> = {
  fa: {
    profile: {
      kicker: 'پروفایل کاربری',
      title: 'پروفایل من',
      lead: 'مدیریت هویت، legacy اکوسیستم، دارایی‌ها، ترجیحات و امنیت حساب شما — همه در یک مکان.',
      clientKeyTitle: 'کلاینت کی',
      clientKeyHint: 'کلید شناسایی کلاینت برای ارتباط با هاب داده هیدروما. این کلید محرمانه است.',
      copy: 'کپی',
      copied: 'کپی شد',
      displayNameTitle: 'نام نمایشی',
      displayNameLabel: 'نام کامل',
      displayNameHint: 'نامی که در پلتفرم نمایش داده می‌شود.',
      save: 'ذخیره',
      saved: 'ذخیره شد',
      privacyNote: 'داده‌های شما محرمانه هستند. هیچ‌گاه فروخته نمی‌شوند و فقط با اطلاع و رضایت شما به اشتراک گذاشته می‌شوند.',
      identityTitle: 'هویت و مشخصات',
      identityBioLabel: 'بیوگرافی',
      identityBioPlaceholder: 'چند جمله درباره خودتان بنویسید...',
      identityBioHint: 'بیوگرافی در صفحه عمومی پروفایل نمایش داده می‌شود.',
      identityOrgLabel: 'سازمان',
      identityOrgPlaceholder: 'نام سازمان یا شرکت',
      identityLocationLabel: 'موقعیت',
      identityLocationPlaceholder: 'شهر، کشور',
      identityMemberSince: 'عضو از',
      identityEdit: 'ویرایش',
      identityViewPublic: 'مشاهده عمومی',
      identityShare: 'اشتراک‌گذاری',
      identityPendingBanner: 'پروفایل شما در حال تأیید است.',
      identityRestrictedBanner: 'دسترسی به این بخش محدود است.',
      legacyTitle: 'Legacy و دستاوردها',
      legacySubtitle: 'شاخص‌های تأثیر زیست‌محیطی و میراث شما در اکو نوژین.',
      legacyCarbon: {
        title: 'کربن ذخیره‌شده',
        value: '—',
        unit: 'تن CO₂e',
        source: 'RothC + Sentinel-2',
        updated: '—',
        empty: 'هنوز داده‌ای از کربن‌گیری ثبت نشده است.',
      },
      legacyArea: {
        title: 'مساحت بازیابی‌شده',
        value: '—',
        unit: 'هکتار',
        source: 'Sentinel-2',
        updated: '—',
        empty: 'هنوز پروژه‌ای ثبت نشده است.',
      },
      legacyWater: {
        title: 'آب صرفه‌جویی‌شده',
        value: '—',
        unit: 'مترمکعب',
        source: 'FAO-56 + ERA5',
        updated: '—',
        empty: 'هنوز داده‌ای از مصرف آب ثبت نشده است.',
      },
      legacyActivity: {
        title: 'فعالیت‌ها',
        value: '—',
        unit: 'گزارش',
        source: 'AuditLog',
        updated: '—',
        empty: 'فعالیتی ثبت نشده است.',
      },
      legacyAchievements: 'دستاوردها',
      legacyMilestones: 'نقاط عطف',
      legacyEmpty: 'هنوز دستاوردی ثبت نشده است.',
      legacyAchievementEmpty: 'هنوز دستاوردی کسب نشده است. فعالیت‌هایتان را ادامه دهید!',
      assetsTitle: 'دارایی‌های متصل',
      assetsLands: {
        title: 'زمین‌ها',
        count: '0',
        empty: 'هنوز زمینی ثبت نشده است.',
        items: [],
      },
      assetsSensors: {
        title: 'سنسورها',
        count: '0',
        empty: 'هیچ سنسوری متصل نیست.',
        items: [],
      },
      assetsWallet: {
        title: 'کیف پول',
        count: '0',
        empty: 'کیف پول هنوز فعال نشده است.',
        items: [],
      },
      assetsApiKeys: {
        title: 'کلیدهای API',
        count: '0',
        empty: 'هیچ کلید API ای ساخته نشده است.',
        items: [],
      },
      assetsProjects: {
        title: 'پروژه‌ها',
        count: '0',
        empty: 'پروژه‌ای ثبت نشده است.',
        items: [],
      },
      assetsManage: 'مدیریت',
      prefsTitle: 'ترجیحات و تنظیمات',
      prefsLanguage: { label: 'زبان', hint: 'زبان نمایش پلتفرم' },
      prefsTimezone: { label: 'منطقه زمانی', hint: 'منطقه زمانی برای نمایش تاریخ و ساعت' },
      prefsUnits: { label: 'واحدها', hint: 'سیستم اندازه‌گیری (متری/امپراتوری)' },
      prefsUnitsWarning: 'توجه: تغییر واحدها باعث بروزرسانی تمام نمایش‌ها در داشبورد می‌شود.',
      prefsTheme: { label: 'تم', hint: 'تم نمایش (روشن/تاریک/سیستم)' },
      prefsNotifications: { label: 'اطلاع‌رسانی‌ها', hint: 'مدیریت اعلان‌های ایمیل، پوش و SMS' },
      prefsDashboard: { label: 'تنظیمات داشبورد', hint: 'ویجت‌ها و چیدمان داشبورد اصلی' },
      prefsSaved: 'تنظیمات ذخیره شد',
      securityTitle: 'امنیت و حساب',
      securityPassword: { label: 'تغییر رمز عبور', description: 'رمز عبور فعلی خود را تغییر دهید.', variant: 'primary' },
      security2fa: { label: 'احراز هویت دو مرحله‌ای', description: 'امنیت حساب با 2FA تقویت کنید.', variant: 'primary' },
      securitySessions: { label: 'مدیریت جلسات', description: 'جلسات فعال را مدیریت و لغو کنید.', variant: 'warning' },
      securityApiKeys: { label: 'کلیدهای API', description: 'کلیدهای API خود را مدیریت کنید.', variant: 'primary' },
      securityExport: { label: 'خروجی داده‌ها', description: 'تمام داده‌های خود را دانلود کنید.', variant: 'primary' },
      securityPrivacy: { label: 'حریم خصوصی', description: 'تنظیمات حریم خصوصی و اشتراک‌گذاری داده.', variant: 'warning' },
      securityDeactivate: { label: 'غیرفعال‌سازی موقت', description: 'حساب خود را به‌طور موقت غیرفعال کنید.', variant: 'warning' },
      securityDelete: { label: 'حذف حساب', description: 'حساب خود را به‌طور دائمی حذف کنید.', variant: 'danger' },
      securityDeleteConfirm: 'آیا مطمئن هستید؟ این عمل غیرقابل بازگشت است.',
      securityDeleteType: 'حذف دائمی',
      securityDeleteFinal: 'برای تأیید، ایمیل خود را وارد کنید:',
      securityDeleteCancelled: 'لغو شد',
    },
    settings: {
      kicker: 'تنظیمات',
      title: 'تنظیمات پلتفرم',
      lead: 'پیکربندی داشبورد، زبان، درگاه API و داده‌های محلی را مدیریت کنید.',
      apiTitle: 'آدرس درگاه API',
      apiHint: 'آدرس درگاه را برای اتصال به سرور موردنظر تنظیم کنید.',
      apiLabel: 'آدرس درگاه',
      apiSave: 'ذخیره آدرس',
      apiSaved: 'آدرس ذخیره شد',
      apiInvalid: 'آدرس باید با http:// یا https:// شروع شود.',
      langTitle: 'زبان رابط',
      langHint: 'زبان و جهت نمایش صفحه را تغییر دهید.',
      dataTitle: 'داده‌های محلی',
      dataHint: 'کلید کاربر، نام نمایشی و تنظیمات ذخیره‌شده در این مرورگر پاک می‌شوند.',
      dataButton: 'پاک‌کردن داده‌های محلی',
      dataDone: 'پاک شد',
      endpointsTitle: 'نقاط اتصال داشبورد',
      endpoints: [
        { method: 'GET', path: '/api/v1/auth/me', desc: 'اطلاعات حساب' },
        { method: 'GET', path: '/api/v1/auth/preferences', desc: 'ترجیحات کاربر' },
        { method: 'PUT', path: '/api/v1/auth/preferences', desc: 'ذخیره ترجیحات' },
        { method: 'GET', path: '/api/v1/hub/runs?user_key=', desc: 'اجراهای مدل' },
      ],
    },
  },
  en: {
    profile: {
      kicker: 'User Profile',
      title: 'My Profile',
      lead: 'Manage your identity, ecosystem legacy, assets, preferences, and account security — all in one place.',
      clientKeyTitle: 'Client Key',
      clientKeyHint: 'Your client identification key for Hydroma data hub communication. This key is secret.',
      copy: 'Copy',
      copied: 'Copied',
      displayNameTitle: 'Display Name',
      displayNameLabel: 'Full Name',
      displayNameHint: 'The name displayed across the platform.',
      save: 'Save',
      saved: 'Saved',
      privacyNote: 'Your data is confidential. It is never sold and only shared with your knowledge and consent.',
      identityTitle: 'Identity & Profile',
      identityBioLabel: 'Bio',
      identityBioPlaceholder: 'Write a few sentences about yourself...',
      identityBioHint: 'Bio is displayed on your public profile page.',
      identityOrgLabel: 'Organization',
      identityOrgPlaceholder: 'Organization or company name',
      identityLocationLabel: 'Location',
      identityLocationPlaceholder: 'City, Country',
      identityMemberSince: 'Member since',
      identityEdit: 'Edit',
      identityViewPublic: 'View Public',
      identityShare: 'Share',
      identityPendingBanner: 'Your profile is pending approval.',
      identityRestrictedBanner: 'Access to this section is restricted.',
      legacyTitle: 'Legacy & Achievements',
      legacySubtitle: 'Environmental impact indicators and your heritage in Eco Nojin.',
      legacyCarbon: {
        title: 'Carbon Sequestered',
        value: '—',
        unit: 't CO₂e',
        source: 'RothC + Sentinel-2',
        updated: '—',
        empty: 'No carbon sequestration data recorded yet.',
      },
      legacyArea: {
        title: 'Area Restored',
        value: '—',
        unit: 'hectares',
        source: 'Sentinel-2',
        updated: '—',
        empty: 'No projects registered yet.',
      },
      legacyWater: {
        title: 'Water Saved',
        value: '—',
        unit: 'm³',
        source: 'FAO-56 + ERA5',
        updated: '—',
        empty: 'No water usage data recorded yet.',
      },
      legacyActivity: {
        title: 'Activity Count',
        value: '—',
        unit: 'reports',
        source: 'AuditLog',
        updated: '—',
        empty: 'No activity recorded yet.',
      },
      legacyAchievements: 'Achievements',
      legacyMilestones: 'Milestones',
      legacyEmpty: 'No achievements recorded yet.',
      legacyAchievementEmpty: 'No achievements earned yet. Keep your activities going!',
      assetsTitle: 'Connected Assets',
      assetsLands: {
        title: 'Lands',
        count: '0',
        empty: 'No lands registered yet.',
        items: [],
      },
      assetsSensors: {
        title: 'Sensors',
        count: '0',
        empty: 'No sensors connected.',
        items: [],
      },
      assetsWallet: {
        title: 'Wallet',
        count: '0',
        empty: 'Wallet not yet activated.',
        items: [],
      },
      assetsApiKeys: {
        title: 'API Keys',
        count: '0',
        empty: 'No API keys created.',
        items: [],
      },
      assetsProjects: {
        title: 'Projects',
        count: '0',
        empty: 'No projects registered.',
        items: [],
      },
      assetsManage: 'Manage',
      prefsTitle: 'Preferences & Settings',
      prefsLanguage: { label: 'Language', hint: 'Platform display language' },
      prefsTimezone: { label: 'Timezone', hint: 'Timezone for date and time display' },
      prefsUnits: { label: 'Units', hint: 'Measurement system (metric/imperial)' },
      prefsUnitsWarning: 'Note: Changing units updates all dashboard displays.',
      prefsTheme: { label: 'Theme', hint: 'Display theme (light/dark/system)' },
      prefsNotifications: { label: 'Notifications', hint: 'Manage email, push, and SMS notifications' },
      prefsDashboard: { label: 'Dashboard Settings', hint: 'Widgets and layout of the main dashboard' },
      prefsSaved: 'Preferences saved',
      securityTitle: 'Security & Account',
      securityPassword: { label: 'Change Password', description: 'Change your current password.', variant: 'primary' },
      security2fa: { label: 'Two-Factor Authentication', description: 'Secure your account with 2FA.', variant: 'primary' },
      securitySessions: { label: 'Session Management', description: 'Manage and revoke active sessions.', variant: 'warning' },
      securityApiKeys: { label: 'API Keys', description: 'Manage your API keys.', variant: 'primary' },
      securityExport: { label: 'Export Data', description: 'Download all your data.', variant: 'primary' },
      securityPrivacy: { label: 'Privacy', description: 'Privacy settings and data sharing.', variant: 'warning' },
      securityDeactivate: { label: 'Temporary Deactivation', description: 'Temporarily deactivate your account.', variant: 'warning' },
      securityDelete: { label: 'Delete Account', description: 'Permanently delete your account.', variant: 'danger' },
      securityDeleteConfirm: 'Are you sure? This action is irreversible.',
      securityDeleteType: 'Permanent Deletion',
      securityDeleteFinal: 'To confirm, enter your email:',
      securityDeleteCancelled: 'Cancelled',
    },
    settings: {
      kicker: 'Settings',
      title: 'Platform Settings',
      lead: 'Manage dashboard configuration, language, API gateway, and local data.',
      apiTitle: 'API Gateway URL',
      apiHint: 'Set the gateway address used by the dashboard.',
      apiLabel: 'Gateway URL',
      apiSave: 'Save URL',
      apiSaved: 'URL saved',
      apiInvalid: 'URL must start with http:// or https://.',
      langTitle: 'Interface Language',
      langHint: 'Change the interface language and text direction.',
      dataTitle: 'Local Data',
      dataHint: 'Clear the client key, display name and settings stored in this browser.',
      dataButton: 'Clear local data',
      dataDone: 'Cleared',
      endpointsTitle: 'Dashboard Endpoints',
      endpoints: [
        { method: 'GET', path: '/api/v1/auth/me', desc: 'Account information' },
        { method: 'GET', path: '/api/v1/auth/preferences', desc: 'User preferences' },
        { method: 'PUT', path: '/api/v1/auth/preferences', desc: 'Save preferences' },
        { method: 'GET', path: '/api/v1/hub/runs?user_key=', desc: 'Model runs' },
      ],
    },
  },
};
