// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/accessibility" | "/[locale]/ai" | "/[locale]/developers" | "/[locale]/evidence" | "/[locale]/home" | "/[locale]/hydroma" | "/[locale]/learn" | "/[locale]/legal" | "/[locale]/market" | "/[locale]/market/bazaars" | "/[locale]/platform" | "/[locale]/services" | "/[locale]/statements" | "/[locale]/status" | "/[locale]/trust"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/accessibility": { "locale": string; }
  "/[locale]/ai": { "locale": string; }
  "/[locale]/developers": { "locale": string; }
  "/[locale]/evidence": { "locale": string; }
  "/[locale]/home": { "locale": string; }
  "/[locale]/hydroma": { "locale": string; }
  "/[locale]/learn": { "locale": string; }
  "/[locale]/legal": { "locale": string; }
  "/[locale]/market": { "locale": string; }
  "/[locale]/market/bazaars": { "locale": string; }
  "/[locale]/platform": { "locale": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/statements": { "locale": string; }
  "/[locale]/status": { "locale": string; }
  "/[locale]/trust": { "locale": string; }
  "/api/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
