// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/accessibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/accessibility">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/accessibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/developers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/developers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/developers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/evidence">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/home">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/hydroma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/hydroma">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/hydroma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/learn">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/market">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/platform">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/services">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/statements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/statements">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/statements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/status">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/trust">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
