"""P0: Fix financial types, add missing columns, fix marketplace models

Revision ID: 1e15be1e1771
Revises: c0585d41d21e
Create Date: 2026-09-15 08:13:50.609264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "1e15be1e1771"
down_revision: Union[str, Sequence[str], None] = "c0585d41d21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calibrationrecorddb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contact_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_messages_email"), ["email"], unique=False)

    op.create_table(
        "ecotransaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("transaction_type", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ecowallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("total_earned", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("total_redeemed", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "errorlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("acked", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hydroma_model_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_key", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hydroma_model_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hydroma_model_runs_model_id"), ["model_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hydroma_model_runs_user_key"), ["user_key"], unique=False
        )
        batch_op.create_index(
            "ix_model_run_user_model_created", ["user_key", "model_id", "created_at"], unique=False
        )

    op.create_table(
        "iot_devices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("device_name", sa.String(length=200), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("sensor_types", sa.JSON(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("platform_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("iot_devices", schema=None) as batch_op:
        batch_op.create_index("ix_iot_device_platform", ["platform_id"], unique=False)
        batch_op.create_index("ix_iot_device_status_type", ["status", "device_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_iot_devices_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_iot_devices_device_type"), ["device_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_iot_devices_platform_id"), ["platform_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_iot_devices_status"), ["status"], unique=False)

    op.create_table(
        "ledgerentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("asset", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledgerentry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledgerentry_account_id"), ["account_id"], unique=False)

    op.create_table(
        "modelversiondb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mrvobservation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.String(length=200), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("sensor_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("data_source", sa.String(length=20), nullable=False),
        sa.Column("qa_status", sa.String(length=20), nullable=False),
        sa.Column("qa_message", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mrvobservation", schema=None) as batch_op:
        batch_op.create_index("ix_mrv_obs_qa_status", ["qa_status"], unique=False)
        batch_op.create_index("ix_mrv_obs_site_level", ["site_id", "level"], unique=False)
        batch_op.create_index(
            "ix_mrv_obs_site_sensor_time", ["site_id", "sensor_type", "observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mrvobservation_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mrvobservation_sensor_type"), ["sensor_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mrvobservation_site_id"), ["site_id"], unique=False)

    op.create_table(
        "newsletter_subscribers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("newsletter_subscribers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_newsletter_subscribers_email"), ["email"], unique=True)

    op.create_table(
        "notification",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_user_id"), ["user_id"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pilot_applications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("province", sa.String(length=80), nullable=False),
        sa.Column("land_hectares", sa.Float(), nullable=True),
        sa.Column("main_crop", sa.String(length=120), nullable=True),
        sa.Column("preferred_channel", sa.String(length=40), nullable=True),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "satellite_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.String(), nullable=True),
        sa.Column("ndvi", sa.Float(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("satellite_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_satellite_analyses_farm_analyzed", ["farm_id", "analyzed_at"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_key"), ["key"], unique=True)

    op.create_table(
        "simulationrun",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.String(length=64), nullable=True),
        sa.Column("scenario", sa.String(length=120), nullable=True),
        sa.Column("area_ha", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("simulationrun", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulationrun_executed_at"), ["executed_at"], unique=False
        )
        batch_op.create_index(
            "ix_simulationrun_site_executed", ["site_id", "executed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_simulationrun_site_id"), ["site_id"], unique=False)

    op.create_table(
        "soil_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.String(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_soil_analyses_farm_analyzed", ["farm_id", "analyzed_at"], unique=False
        )

    op.create_table(
        "topography_analysis_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=True),
        sa.Column("data", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("platform_id", sa.String(), nullable=True),
        sa.Column("is_email_verified", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_platform_id"), ["platform_id"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "carbon_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("platform_id", sa.String(), nullable=True),
        sa.Column("project_type", sa.String(length=80), nullable=True),
        sa.Column("area_hectares", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("credits_issued", sa.Float(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("verification_detail", sa.Text(), nullable=True),
        sa.Column("estimated_carbon_tonnes", sa.Float(), nullable=True),
        sa.Column("annual_rate_tonnes", sa.Float(), nullable=True),
        sa.Column("methodology", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=80), nullable=True),
        sa.Column("duration_years", sa.Integer(), nullable=True),
        sa.Column("price_per_tonne_usd", sa.Float(), nullable=True),
        sa.Column("estimated_revenue_usd", sa.Float(), nullable=True),
        sa.Column("confidence", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("carbon_projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_carbon_projects_platform_id"), ["platform_id"], unique=False
        )
        batch_op.create_index(
            "ix_carbon_projects_platform_status", ["platform_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_carbon_projects_project_id"), ["project_id"], unique=True
        )
        batch_op.create_index("ix_carbon_projects_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "decisionrecommendationdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "land_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("area_ha", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.CheckConstraint("name != ''", name="ck_land_profile_name_not_empty"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="_user_land_name_uc"),
    )
    op.create_table(
        "monitoringdatadb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nojincalibrationrecorddb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nojinfieldtrialdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("provider_user_id", sa.String(), nullable=True),
        sa.Column("access_token_encrypted", sa.String(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.String(), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_provider_oauth"),
    )
    op.create_table(
        "optimizationresultdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", "VIEWER", name="organizationrole"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INVITED", "REMOVED", name="organizationstatus"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_org_user"),
    )
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.create_index("ix_org_membership_org_status", ["org_id", "status"], unique=False)
        batch_op.create_index("ix_org_membership_user_status", ["user_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_organization_memberships_org_id"), ["org_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organization_memberships_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "scenariodb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenariorun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nojin_application_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("land_profile_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["land_profile_id"],
            ["land_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nojin_application_plans", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nojin_app_plan_profile_created", ["land_profile_id", "created_at"], unique=False
        )

    op.create_table(
        "scenarioresultdb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scenario_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_run_id"],
            ["scenariorun.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("landscape_villages")
    with op.batch_alter_table("tourism_guides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_guide_user"))
        batch_op.drop_index(batch_op.f("idx_guide_village"))

    op.drop_table("tourism_guides")
    op.drop_table("landscape_funds")
    with op.batch_alter_table("marketplace_sellers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_seller_status"))
        batch_op.drop_index(batch_op.f("idx_seller_user"))
        batch_op.drop_index(batch_op.f("idx_seller_village"))

    op.drop_table("marketplace_sellers")
    with op.batch_alter_table("landscape_governance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_gov_role"))
        batch_op.drop_index(batch_op.f("idx_gov_user"))
        batch_op.drop_index(batch_op.f("idx_gov_village"))

    op.drop_table("landscape_governance")
    op.drop_table("marketplace_commission_rules")
    with op.batch_alter_table("tourism_bookings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_booking_guest"))
        batch_op.drop_index(batch_op.f("idx_booking_status"))
        batch_op.drop_index(batch_op.f("idx_booking_tour"))

    op.drop_table("tourism_bookings")
    with op.batch_alter_table("marketplace_products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_product_seller"))
        batch_op.drop_index(batch_op.f("idx_product_village"))

    op.drop_table("marketplace_products")
    with op.batch_alter_table("tourism_tours", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_tour_guide"))
        batch_op.drop_index(batch_op.f("idx_tour_status"))
        batch_op.drop_index(batch_op.f("idx_tour_village"))

    op.drop_table("tourism_tours")
    with op.batch_alter_table("marketplace_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_order_buyer"))
        batch_op.drop_index(batch_op.f("idx_order_status"))

    op.drop_table("marketplace_orders")
    with op.batch_alter_table("landscape_fund_distributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_dist_fund"))
        batch_op.drop_index(batch_op.f("idx_dist_status"))
        batch_op.drop_index(batch_op.f("idx_dist_village"))

    op.drop_table("landscape_fund_distributions")
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.alter_column("actor_id", existing_type=sa.VARCHAR(length=100), nullable=True)
        batch_op.alter_column("resource_type", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.drop_index(batch_op.f("ix_auditlog_actor_time"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auditlog_actor_time"), ["actor_id", "created_at"], unique=False
        )
        batch_op.alter_column("resource_type", existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.alter_column("actor_id", existing_type=sa.VARCHAR(length=100), nullable=False)

    op.create_table(
        "landscape_fund_distributions",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("fund_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=18, scale=2), nullable=False),
        sa.Column("purpose", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("recipient_user_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("recipient_organization", sa.VARCHAR(length=200), nullable=True),
        sa.Column("proposed_by", sa.VARCHAR(length=36), nullable=False),
        sa.Column("approved_by", sa.VARCHAR(length=36), nullable=True),
        sa.Column("approved_at", sa.DATETIME(), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True
        ),
        sa.Column("blockchain_tx_hash", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["fund_id"],
            ["landscape_funds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("landscape_fund_distributions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_dist_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_dist_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_dist_fund"), ["fund_id"], unique=False)

    op.create_table(
        "marketplace_orders",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_number", sa.VARCHAR(length=50), nullable=False),
        sa.Column("buyer_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("subtotal", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "platform_fee",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "landscape_fee",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("total", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True
        ),
        sa.Column(
            "payment_status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending'"),
            nullable=True,
        ),
        sa.Column("shipping_address", sqlite.JSON(), nullable=True),
        sa.Column("blockchain_tx_hash", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    with op.batch_alter_table("marketplace_orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_order_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_order_buyer"), ["buyer_id"], unique=False)

    op.create_table(
        "tourism_tours",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("guide_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("title", sa.VARCHAR(length=300), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=300), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("tour_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("duration_hours", sa.INTEGER(), nullable=False),
        sa.Column("max_participants", sa.INTEGER(), server_default=sa.text("(10)"), nullable=True),
        sa.Column("min_participants", sa.INTEGER(), server_default=sa.text("2"), nullable=True),
        sa.Column(
            "difficulty", sa.VARCHAR(length=20), server_default=sa.text("'moderate'"), nullable=True
        ),
        sa.Column("price_per_person", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("ecological_capacity", sa.INTEGER(), nullable=True),
        sa.Column("current_bookings", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending_approval'"),
            nullable=True,
        ),
        sa.Column("is_regenerative", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column("regenerative_activity", sa.TEXT(), nullable=True),
        sa.Column("total_bookings", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["tourism_guides.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("tourism_tours", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_tour_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_tour_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_tour_guide"), ["guide_id"], unique=False)

    op.create_table(
        "marketplace_products",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("seller_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("name", sa.VARCHAR(length=300), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=300), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("category", sa.VARCHAR(length=100), nullable=False),
        sa.Column("price", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("stock", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'draft'"), nullable=True
        ),
        sa.Column("pgs_certified", sa.BOOLEAN(), server_default=sa.text("0"), nullable=True),
        sa.Column("organic", sa.BOOLEAN(), server_default=sa.text("0"), nullable=True),
        sa.Column("story", sa.TEXT(), nullable=True),
        sa.Column("metadata_json", sqlite.JSON(), nullable=True),
        sa.Column("sales_count", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["marketplace_sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("marketplace_products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_product_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_product_seller"), ["seller_id"], unique=False)

    op.create_table(
        "tourism_bookings",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("booking_number", sa.VARCHAR(length=50), nullable=False),
        sa.Column("tour_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("guest_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("participants_count", sa.INTEGER(), nullable=False),
        sa.Column("tour_date", sa.DATETIME(), nullable=False),
        sa.Column("subtotal", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "platform_fee",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "landscape_fee",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "insurance_fee",
            sa.NUMERIC(precision=15, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("total", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True
        ),
        sa.Column(
            "payment_status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending'"),
            nullable=True,
        ),
        sa.Column("blockchain_tx_hash", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "regenerative_completed", sa.BOOLEAN(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tour_id"],
            ["tourism_tours.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_number"),
    )
    with op.batch_alter_table("tourism_bookings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_booking_tour"), ["tour_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_booking_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_booking_guest"), ["guest_id"], unique=False)

    op.create_table(
        "marketplace_commission_rules",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("category", sa.VARCHAR(length=100), nullable=True),
        sa.Column("platform_fee_bps", sa.INTEGER(), server_default=sa.text("(300)"), nullable=True),
        sa.Column(
            "landscape_fee_bps", sa.INTEGER(), server_default=sa.text("(100)"), nullable=True
        ),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "landscape_governance",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column("term_start", sa.DATE(), nullable=True),
        sa.Column("term_end", sa.DATE(), nullable=True),
        sa.Column(
            "elected_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("phone", sa.VARCHAR(length=20), nullable=True),
        sa.Column("email", sa.VARCHAR(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("landscape_governance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_gov_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_gov_user"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_gov_role"), ["role"], unique=False)

    op.create_table(
        "marketplace_sellers",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("shop_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("shop_description", sa.TEXT(), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True
        ),
        sa.Column("is_verified", sa.BOOLEAN(), server_default=sa.text("0"), nullable=True),
        sa.Column("certifications", sqlite.JSON(), nullable=True),
        sa.Column("total_sales", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marketplace_sellers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_seller_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_seller_user"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_seller_status"), ["status"], unique=False)

    op.create_table(
        "landscape_funds",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("contract_address", sa.VARCHAR(length=100), nullable=True),
        sa.Column("fee_bps", sa.INTEGER(), server_default=sa.text("(100)"), nullable=True),
        sa.Column(
            "total_collected",
            sa.NUMERIC(precision=18, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "total_distributed",
            sa.NUMERIC(precision=18, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "pending_balance",
            sa.NUMERIC(precision=18, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("currency", sa.VARCHAR(length=3), server_default=sa.text("'IRR'"), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("village_id"),
    )
    op.create_table(
        "tourism_guides",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("full_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("bio", sa.TEXT(), nullable=True),
        sa.Column("languages", sqlite.JSON(), nullable=True),
        sa.Column("specialties", sqlite.JSON(), nullable=True),
        sa.Column("license_number", sa.VARCHAR(length=100), nullable=True),
        sa.Column("is_verified", sa.BOOLEAN(), server_default=sa.text("0"), nullable=True),
        sa.Column("total_tours", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tourism_guides", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_guide_village"), ["village_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_guide_user"), ["user_id"], unique=False)

    op.create_table(
        "landscape_villages",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("village_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("region", sa.VARCHAR(length=100), nullable=False),
        sa.Column("country", sa.VARCHAR(length=100), server_default=sa.text("'IR'"), nullable=True),
        sa.Column("coordinates", sqlite.JSON(), nullable=True),
        sa.Column("geo_boundary", sqlite.JSON(), nullable=True),
        sa.Column("brand_name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column("active_modules", sqlite.JSON(), nullable=True),
        sa.Column("total_members", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("active_sellers", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("active_tour_guides", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "monthly_gmv",
            sa.NUMERIC(precision=18, scale=2),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("ecological_metrics_data", sqlite.JSON(), nullable=True),
        sa.Column("smart_contract_address", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("village_id"),
    )
    op.drop_table("scenarioresultdb")
    with op.batch_alter_table("nojin_application_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_nojin_app_plan_profile_created")

    op.drop_table("nojin_application_plans")
    op.drop_table("scenariorun")
    op.drop_table("scenariodb")
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_memberships_org_id"))
        batch_op.drop_index("ix_org_membership_user_status")
        batch_op.drop_index("ix_org_membership_org_status")

    op.drop_table("organization_memberships")
    op.drop_table("optimizationresultdb")
    op.drop_table("oauth_connections")
    op.drop_table("nojinfieldtrialdb")
    op.drop_table("nojincalibrationrecorddb")
    op.drop_table("monitoringdatadb")
    op.drop_table("land_profiles")
    op.drop_table("decisionrecommendationdb")
    with op.batch_alter_table("carbon_projects", schema=None) as batch_op:
        batch_op.drop_index("ix_carbon_projects_user_status")
        batch_op.drop_index(batch_op.f("ix_carbon_projects_project_id"))
        batch_op.drop_index("ix_carbon_projects_platform_status")
        batch_op.drop_index(batch_op.f("ix_carbon_projects_platform_id"))

    op.drop_table("carbon_projects")
    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_platform_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("topography_analysis_results")
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_soil_analyses_farm_analyzed")

    op.drop_table("soil_analyses")
    with op.batch_alter_table("simulationrun", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulationrun_site_id"))
        batch_op.drop_index("ix_simulationrun_site_executed")
        batch_op.drop_index(batch_op.f("ix_simulationrun_executed_at"))

    op.drop_table("simulationrun")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_key"))

    op.drop_table("settings")
    with op.batch_alter_table("satellite_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_satellite_analyses_farm_analyzed")

    op.drop_table("satellite_analyses")
    op.drop_table("product")
    op.drop_table("pilot_applications")
    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_user_id"))

    op.drop_table("notification")
    with op.batch_alter_table("newsletter_subscribers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_newsletter_subscribers_email"))

    op.drop_table("newsletter_subscribers")
    with op.batch_alter_table("mrvobservation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mrvobservation_site_id"))
        batch_op.drop_index(batch_op.f("ix_mrvobservation_sensor_type"))
        batch_op.drop_index(batch_op.f("ix_mrvobservation_observed_at"))
        batch_op.drop_index("ix_mrv_obs_site_sensor_time")
        batch_op.drop_index("ix_mrv_obs_site_level")
        batch_op.drop_index("ix_mrv_obs_qa_status")

    op.drop_table("mrvobservation")
    op.drop_table("modelversiondb")
    with op.batch_alter_table("ledgerentry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledgerentry_account_id"))

    op.drop_table("ledgerentry")
    with op.batch_alter_table("iot_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_iot_devices_status"))
        batch_op.drop_index(batch_op.f("ix_iot_devices_platform_id"))
        batch_op.drop_index(batch_op.f("ix_iot_devices_device_type"))
        batch_op.drop_index(batch_op.f("ix_iot_devices_created_at"))
        batch_op.drop_index("ix_iot_device_status_type")
        batch_op.drop_index("ix_iot_device_platform")

    op.drop_table("iot_devices")
    with op.batch_alter_table("hydroma_model_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_model_run_user_model_created")
        batch_op.drop_index(batch_op.f("ix_hydroma_model_runs_user_key"))
        batch_op.drop_index(batch_op.f("ix_hydroma_model_runs_model_id"))

    op.drop_table("hydroma_model_runs")
    op.drop_table("farms")
    op.drop_table("errorlog")
    op.drop_table("ecowallet")
    op.drop_table("ecotransaction")
    with op.batch_alter_table("contact_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_messages_email"))

    op.drop_table("contact_messages")
    op.drop_table("calibrationrecorddb")
    op.drop_table("ai_conversations")
    # ### end Alembic commands ###
