"""P0: Add FinIdempotencyKey table for idempotency

Revision ID: 425ba660dd2d
Revises: 1e15be1e1771
Create Date: 2026-09-15 08:25:08.678400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "425ba660dd2d"
down_revision: Union[str, Sequence[str], None] = "1e15be1e1771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fin_idempotency_key",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("route", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fin_idempotency_key", schema=None) as batch_op:
        batch_op.create_index("ix_fin_idempotency_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fin_idempotency_key_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ix_fin_idempotency_user_key", ["user_id", "key"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fin_idempotency_key", schema=None) as batch_op:
        batch_op.drop_index("ix_fin_idempotency_user_key")
        batch_op.drop_index(batch_op.f("ix_fin_idempotency_key_user_id"))
        batch_op.drop_index("ix_fin_idempotency_expires")

    op.drop_table("fin_idempotency_key")
    # ### end Alembic commands ###
