"""P2: Add inventory/WMS models

Revision ID: 718969b7e01d
Revises: 9c8b48af79be
Create Date: 2026-09-15 10:26:02.956357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718969b7e01d'
down_revision: Union[str, Sequence[str], None] = '9c8b48af79be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['inv_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_category_code'), ['code'], unique=True)

    op.create_table('inv_valuation_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inv_warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('gps_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('gps_lon', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_warehouse_code'), ['code'], unique=True)

    op.create_table('inv_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('aisle', sa.String(length=10), nullable=True),
    sa.Column('rack', sa.String(length=10), nullable=True),
    sa.Column('shelf', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('max_capacity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_pickable', sa.Boolean(), nullable=True),
    sa.Column('is_receivable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_location_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_location_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inv_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_trackable', sa.Boolean(), nullable=True),
    sa.Column('is_perishable', sa.Boolean(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inv_category.id'], ),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_sku', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_sku_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_sku_sku_code'), ['sku_code'], unique=True)

    op.create_table('inv_stocktake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stocktake_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stocktake_type', sa.String(length=20), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counted_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_stocktake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_stocktake_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stocktake_stocktake_number'), ['stocktake_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inv_stocktake_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inv_lot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('manufacture_country', sa.String(length=2), nullable=True),
    sa.Column('supplier_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_lot_number', sa.String(length=50), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['inv_sku.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'lot_number', name='uq_lot_sku_lot')
    )
    with op.batch_alter_table('inv_lot', schema=None) as batch_op:
        batch_op.create_index('ix_inv_lot_expiry', ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_lot_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_lot_lot_number'), ['lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_lot_sku_code'), ['sku_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_lot_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('ix_inv_lot_status', ['quality_status'], unique=False)

    op.create_table('inv_inventory_balance',
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('blocked', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('in_transit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inv_lot.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['inv_sku.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('sku_id', 'warehouse_id', 'location_id', 'lot_id')
    )
    with op.batch_alter_table('inv_inventory_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_inventory_balance_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_inventory_balance_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_inventory_balance_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_inventory_balance_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inv_reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('reference_line_id', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inv_lot.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['inv_sku.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_reservation', schema=None) as batch_op:
        batch_op.create_index('ix_inv_reservation_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_reservation_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_reservation_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_reservation_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('ix_inv_reservation_sku_warehouse', ['sku_id', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_reservation_status'), ['status'], unique=False)
        batch_op.create_index('ix_inv_reservation_status_expires', ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_reservation_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inv_stock_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['inv_location.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['inv_warehouse.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inv_lot.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['inv_sku.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['inv_location.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['inv_warehouse.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_stock_movement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stock_movement_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stock_movement_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index('ix_inv_stock_movement_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stock_movement_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('ix_inv_stock_movement_sku_warehouse', ['sku_id', 'warehouse_id'], unique=False)
        batch_op.create_index('ix_inv_stock_movement_type_date', ['movement_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stock_movement_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inv_stocktake_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stocktake_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('system_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('variance_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('counted_by', sa.String(length=50), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inv_lot.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['inv_sku.id'], ),
    sa.ForeignKeyConstraint(['stocktake_id'], ['inv_stocktake.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_stocktake_line', schema=None) as batch_op:
        batch_op.create_index('ix_inv_stocktake_line_sku', ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stocktake_line_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('ix_inv_stocktake_line_stocktake', ['stocktake_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_stocktake_line_stocktake_id'), ['stocktake_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inv_stocktake_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_stocktake_line_stocktake_id'))
        batch_op.drop_index('ix_inv_stocktake_line_stocktake')
        batch_op.drop_index(batch_op.f('ix_inv_stocktake_line_sku_id'))
        batch_op.drop_index('ix_inv_stocktake_line_sku')

    op.drop_table('inv_stocktake_line')
    with op.batch_alter_table('inv_stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_stock_movement_warehouse_id'))
        batch_op.drop_index('ix_inv_stock_movement_type_date')
        batch_op.drop_index('ix_inv_stock_movement_sku_warehouse')
        batch_op.drop_index(batch_op.f('ix_inv_stock_movement_sku_id'))
        batch_op.drop_index('ix_inv_stock_movement_reference')
        batch_op.drop_index(batch_op.f('ix_inv_stock_movement_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inv_stock_movement_created_by'))
        batch_op.drop_index(batch_op.f('ix_inv_stock_movement_created_at'))

    op.drop_table('inv_stock_movement')
    with op.batch_alter_table('inv_reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_reservation_warehouse_id'))
        batch_op.drop_index('ix_inv_reservation_status_expires')
        batch_op.drop_index(batch_op.f('ix_inv_reservation_status'))
        batch_op.drop_index('ix_inv_reservation_sku_warehouse')
        batch_op.drop_index(batch_op.f('ix_inv_reservation_sku_id'))
        batch_op.drop_index(batch_op.f('ix_inv_reservation_reference_type'))
        batch_op.drop_index(batch_op.f('ix_inv_reservation_reference_id'))
        batch_op.drop_index('ix_inv_reservation_reference')

    op.drop_table('inv_reservation')
    with op.batch_alter_table('inv_inventory_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_inventory_balance_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inv_inventory_balance_sku_id'))
        batch_op.drop_index(batch_op.f('ix_inv_inventory_balance_lot_id'))
        batch_op.drop_index(batch_op.f('ix_inv_inventory_balance_location_id'))

    op.drop_table('inv_inventory_balance')
    with op.batch_alter_table('inv_lot', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_lot_status')
        batch_op.drop_index(batch_op.f('ix_inv_lot_sku_id'))
        batch_op.drop_index(batch_op.f('ix_inv_lot_sku_code'))
        batch_op.drop_index(batch_op.f('ix_inv_lot_lot_number'))
        batch_op.drop_index(batch_op.f('ix_inv_lot_expiry_date'))
        batch_op.drop_index('ix_inv_lot_expiry')

    op.drop_table('inv_lot')
    with op.batch_alter_table('inv_stocktake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_stocktake_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inv_stocktake_stocktake_number'))
        batch_op.drop_index(batch_op.f('ix_inv_stocktake_status'))

    op.drop_table('inv_stocktake')
    with op.batch_alter_table('inv_sku', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_sku_sku_code'))
        batch_op.drop_index(batch_op.f('ix_inv_sku_category_id'))

    op.drop_table('inv_sku')
    with op.batch_alter_table('inv_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_location_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inv_location_code'))

    op.drop_table('inv_location')
    with op.batch_alter_table('inv_warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_warehouse_code'))

    op.drop_table('inv_warehouse')
    op.drop_table('inv_valuation_method')
    with op.batch_alter_table('inv_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_category_code'))

    op.drop_table('inv_category')
    # ### end Alembic commands ###
