"""P1: Add IntOutboxEvent table for outbox pattern

Revision ID: 9c8b48af79be
Revises: e6f7a8b9c0d1
Create Date: 2026-09-15 09:48:39.634358

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c8b48af79be"
down_revision: str | Sequence[str] | None = "e6f7a8b9c0d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index("ix_audit_event_actor_action", ["actor_id", "action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index("ix_audit_event_correlation", ["correlation_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index("ix_audit_event_created", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_event_request_id"), ["request_id"], unique=False)
        batch_op.create_index(
            "ix_audit_event_resource", ["resource_type", "resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_event_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_event_resource_type"), ["resource_type"], unique=False
        )

    op.create_table(
        "fin_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("asset", sa.String(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["fin_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fin_account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fin_account_code"), ["code"], unique=True)

    op.create_table(
        "fin_journal_batch",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_number", sa.String(length=50), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_posted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fin_journal_batch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fin_journal_batch_batch_number"), ["batch_number"], unique=True
        )

    op.create_table(
        "fin_journal_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("asset", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fin_journal_entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fin_journal_entry_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fin_journal_entry_batch_id"), ["batch_id"], unique=False
        )

    op.create_table(
        "int_outbox_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aggregate_type", sa.String(), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("int_outbox_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_int_outbox_event_aggregate_id"), ["aggregate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_int_outbox_event_aggregate_type"), ["aggregate_type"], unique=False
        )
        batch_op.create_index(
            "ix_int_outbox_unprocessed",
            ["created_at"],
            unique=False,
            postgresql_where="processed_at IS NULL",
        )

    with op.batch_alter_table("marketplace_escrow_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_escrow_order"))
        batch_op.drop_index(batch_op.f("idx_escrow_payment"))
        batch_op.drop_index(batch_op.f("ix_marketplace_escrow_entries_marketplace_id"))
        batch_op.drop_index(batch_op.f("ix_marketplace_escrow_entries_seller_id"))

    op.drop_table("marketplace_escrow_entries")
    with op.batch_alter_table("marketplace_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_mpay_order"))
        batch_op.drop_index(batch_op.f("idx_mpay_status"))
        batch_op.drop_index(batch_op.f("ix_marketplace_payments_authority"))
        batch_op.drop_index(batch_op.f("ix_marketplace_payments_user_id"))

    op.drop_table("marketplace_payments")
    with op.batch_alter_table("quality_inspections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_qi_product"))
        batch_op.drop_index(batch_op.f("ix_quality_inspections_marketplace_id"))

    op.drop_table("quality_inspections")
    with op.batch_alter_table("disputes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_dispute_order"))
        batch_op.drop_index(batch_op.f("idx_dispute_status"))
        batch_op.drop_index(batch_op.f("ix_disputes_marketplace_id"))

    op.drop_table("disputes")
    with op.batch_alter_table("quality_certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_qc_inspection"))
        batch_op.drop_index(batch_op.f("idx_qc_product"))

    op.drop_table("quality_certificates")
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_shipment_order"))
        batch_op.drop_index(batch_op.f("ix_shipments_tracking_code"))

    op.drop_table("shipments")
    with op.batch_alter_table("marketplace_founders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_founder_marketplace"))
        batch_op.drop_index(batch_op.f("idx_founder_user"))

    op.drop_table("marketplace_founders")
    with op.batch_alter_table("shipment_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_shipment_event_shipment"))

    op.drop_table("shipment_events")
    with op.batch_alter_table("dispute_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_dispute_event_dispute"))

    op.drop_table("dispute_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispute_events",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("dispute_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("event", sa.VARCHAR(length=40), nullable=False),
        sa.Column("actor", sa.VARCHAR(length=36), nullable=True),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dispute_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_dispute_event_dispute"), ["dispute_id"], unique=False)

    op.create_table(
        "shipment_events",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("shipment_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("actor", sa.VARCHAR(length=36), nullable=True),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shipment_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_shipment_event_shipment"), ["shipment_id"], unique=False
        )

    op.create_table(
        "marketplace_founders",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("marketplace_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column(
            "role", sa.VARCHAR(length=20), server_default=sa.text("'founder'"), nullable=False
        ),
        sa.Column("equity_share", sa.NUMERIC(precision=5, scale=2), nullable=True),
        sa.Column("contribution_type", sa.VARCHAR(length=20), nullable=True),
        sa.Column("contribution_amount", sa.NUMERIC(precision=12, scale=2), nullable=True),
        sa.Column("identity_verified", sa.BOOLEAN(), nullable=True),
        sa.Column("identity_verification_date", sa.DATETIME(), nullable=True),
        sa.Column("verification_method", sa.VARCHAR(length=40), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("joined_at", sa.DATETIME(), nullable=True),
        sa.Column("left_at", sa.DATETIME(), nullable=True),
        sa.Column("wallet_address", sa.VARCHAR(length=42), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.CheckConstraint(
            "equity_share >= 0 AND equity_share <= 100", name=op.f("ck_equity_share")
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("marketplace_id", "user_id", name=op.f("uq_marketplace_user")),
    )
    with op.batch_alter_table("marketplace_founders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_founder_user"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_founder_marketplace"), ["marketplace_id"], unique=False
        )

    op.create_table(
        "shipments",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("carrier", sa.VARCHAR(length=60), nullable=True),
        sa.Column("tracking_code", sa.VARCHAR(length=60), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("origin", sa.VARCHAR(length=200), nullable=True),
        sa.Column("destination", sa.VARCHAR(length=200), nullable=True),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shipments_tracking_code"), ["tracking_code"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_shipment_order"), ["order_id"], unique=False)

    op.create_table(
        "quality_certificates",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("inspection_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("product_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("standard", sa.VARCHAR(length=60), nullable=False),
        sa.Column("issued_at", sa.DATETIME(), nullable=True),
        sa.Column("valid_until", sa.DATETIME(), nullable=True),
        sa.Column("issued_by", sa.VARCHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_certificates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_qc_product"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_qc_inspection"), ["inspection_id"], unique=False)

    op.create_table(
        "disputes",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("marketplace_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("complainant_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("respondent_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("category", sa.VARCHAR(length=30), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'open'"), nullable=False
        ),
        sa.Column("resolution", sa.TEXT(), nullable=True),
        sa.Column("resolved_by", sa.VARCHAR(length=36), nullable=True),
        sa.Column("resolved_at", sa.DATETIME(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("disputes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_disputes_marketplace_id"), ["marketplace_id"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_dispute_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_dispute_order"), ["order_id"], unique=False)

    op.create_table(
        "quality_inspections",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("product_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("marketplace_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("inspector_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("inspection_type", sa.VARCHAR(length=30), nullable=False),
        sa.Column("score", sa.FLOAT(), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_inspections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quality_inspections_marketplace_id"), ["marketplace_id"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_qi_product"), ["product_id"], unique=False)

    op.create_table(
        "marketplace_payments",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("gateway", sa.VARCHAR(length=20), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "currency", sa.VARCHAR(length=8), server_default=sa.text("'IRR'"), nullable=False
        ),
        sa.Column(
            "status", sa.VARCHAR(length=24), server_default=sa.text("'initiated'"), nullable=False
        ),
        sa.Column(
            "escrow_status", sa.VARCHAR(length=24), server_default=sa.text("'none'"), nullable=False
        ),
        sa.Column("authority", sa.VARCHAR(length=100), nullable=True),
        sa.Column("ref_id", sa.VARCHAR(length=60), nullable=True),
        sa.Column("card_pan_masked", sa.VARCHAR(length=30), nullable=True),
        sa.Column("tracking_code", sa.VARCHAR(length=60), nullable=True),
        sa.Column("redirect_url", sa.TEXT(), nullable=True),
        sa.Column("gateway_meta", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marketplace_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_marketplace_payments_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_payments_authority"), ["authority"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_mpay_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_mpay_order"), ["order_id"], unique=False)

    op.create_table(
        "marketplace_escrow_entries",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("payment_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("seller_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("marketplace_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("entry_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column(
            "currency", sa.VARCHAR(length=8), server_default=sa.text("'IRR'"), nullable=False
        ),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("actor_id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marketplace_escrow_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_marketplace_escrow_entries_seller_id"), ["seller_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_escrow_entries_marketplace_id"),
            ["marketplace_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("idx_escrow_payment"), ["payment_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_escrow_order"), ["order_id"], unique=False)

    with op.batch_alter_table("int_outbox_event", schema=None) as batch_op:
        batch_op.drop_index("ix_int_outbox_unprocessed", postgresql_where="processed_at IS NULL")
        batch_op.drop_index(batch_op.f("ix_int_outbox_event_aggregate_type"))
        batch_op.drop_index(batch_op.f("ix_int_outbox_event_aggregate_id"))

    op.drop_table("int_outbox_event")
    with op.batch_alter_table("fin_journal_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fin_journal_entry_batch_id"))
        batch_op.drop_index(batch_op.f("ix_fin_journal_entry_account_id"))

    op.drop_table("fin_journal_entry")
    with op.batch_alter_table("fin_journal_batch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fin_journal_batch_batch_number"))

    op.drop_table("fin_journal_batch")
    with op.batch_alter_table("fin_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fin_account_code"))

    op.drop_table("fin_account")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_resource_type"))
        batch_op.drop_index(batch_op.f("ix_audit_event_resource_id"))
        batch_op.drop_index("ix_audit_event_resource")
        batch_op.drop_index(batch_op.f("ix_audit_event_request_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_created_at"))
        batch_op.drop_index("ix_audit_event_created")
        batch_op.drop_index(batch_op.f("ix_audit_event_correlation_id"))
        batch_op.drop_index("ix_audit_event_correlation")
        batch_op.drop_index(batch_op.f("ix_audit_event_actor_id"))
        batch_op.drop_index("ix_audit_event_actor_action")

    op.drop_table("audit_event")
    # ### end Alembic commands ###
