"""phase0 baseline unified schema

Revision ID: ce9bf9a53ae1
Revises:
Create Date: 2026-08-15 04:16:08.336781

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce9bf9a53ae1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=False,
            comment="animal, plant, mineral, microbial",
        ),
        sa.Column("c_n_ratio", sa.Float(), nullable=True, comment="Carbon to Nitrogen ratio"),
        sa.Column("ph", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_materials_name"), ["name"], unique=False)

    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scientific_name", sa.String(length=150), nullable=False),
        sa.Column("local_name", sa.String(length=100), nullable=True),
        sa.Column(
            "category", sa.String(length=50), nullable=False, comment="e.g., crop, tree, medicinal"
        ),
        sa.Column("water_need", sa.String(length=20), nullable=True, comment="low, medium, high"),
        sa.Column("drought_tolerance", sa.String(length=20), nullable=True),
        sa.Column("salinity_tolerance", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plants_scientific_name"), ["scientific_name"], unique=False
        )

    op.create_table(
        "recommendation_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=True),
        sa.Column("context_type", sa.String(length=50), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_cache_context_hash"), ["context_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_recommendation_cache_id"), ["id"], unique=False)

    op.create_table(
        "soil_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("texture", sa.String(length=50), nullable=True, comment="e.g., Sandy Loam, Clay"),
        sa.Column("ph", sa.Float(), nullable=True),
        sa.Column("ec", sa.Float(), nullable=True, comment="Electrical Conductivity (dS/m)"),
        sa.Column("organic_matter", sa.Float(), nullable=True, comment="Percentage"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("soil_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_soil_profiles_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("avatar_url", sa.String(length=2000), nullable=True),
        sa.Column("is_email_verified", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("accept_tos", sa.Boolean(), nullable=True),
        sa.Column("accept_privacy", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "ai_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("asked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_conversations_asked_at"), ["asked_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ai_conversations_id"), ["id"], unique=False)

    op.create_table(
        "carbon_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("project_type", sa.String(length=50), nullable=True),
        sa.Column("area_hectares", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("credits_issued", sa.Float(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    with op.batch_alter_table("carbon_projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_carbon_projects_id"), ["id"], unique=False)

    op.create_table(
        "eco_wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("total_earned", sa.Float(), nullable=True),
        sa.Column("total_redeemed", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("eco_wallets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eco_wallets_id"), ["id"], unique=False)

    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("area_hectares", sa.Float(), nullable=False),
        sa.Column("soil_type", sa.String(length=100), nullable=True),
        sa.Column("climate_zone", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_farms_id"), ["id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_password_reset_tokens_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_password_reset_tokens_token"), ["token"], unique=True)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("producer_id", sa.Integer(), nullable=True),
        sa.Column("is_organic", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_id"), ["id"], unique=False)

    op.create_table(
        "eco_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("balance_after", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["wallet_id"], ["eco_wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eco_transactions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eco_transactions_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_eco_transactions_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_eco_transactions_transaction_id"), ["transaction_id"], unique=True
        )

    op.create_table(
        "satellite_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("ndvi", sa.Float(), nullable=True),
        sa.Column("evi", sa.Float(), nullable=True),
        sa.Column("savi", sa.Float(), nullable=True),
        sa.Column("ndwi", sa.Float(), nullable=True),
        sa.Column("nbr", sa.Float(), nullable=True),
        sa.Column("satellite", sa.String(length=50), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("satellite_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_satellite_analyses_analyzed_at"), ["analyzed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_satellite_analyses_id"), ["id"], unique=False)

    op.create_table(
        "scenario_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("baseline_temp", sa.Float(), nullable=True),
        sa.Column("baseline_precip", sa.Float(), nullable=True),
        sa.Column("scenario", sa.String(length=20), nullable=True),
        sa.Column("target_year", sa.Integer(), nullable=True),
        sa.Column("projected_temp", sa.Float(), nullable=True),
        sa.Column("projected_precip", sa.Float(), nullable=True),
        sa.Column("temp_change", sa.Float(), nullable=True),
        sa.Column("precip_change_percent", sa.Float(), nullable=True),
        sa.Column("drought_risk_index", sa.Float(), nullable=True),
        sa.Column("impact_assessment", sa.JSON(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("run_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenario_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenario_runs_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scenario_runs_run_at"), ["run_at"], unique=False)

    op.create_table(
        "soil_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ph", sa.Float(), nullable=True),
        sa.Column("organic_matter", sa.Float(), nullable=True),
        sa.Column("nitrogen", sa.Float(), nullable=True),
        sa.Column("phosphorus", sa.Float(), nullable=True),
        sa.Column("potassium", sa.Float(), nullable=True),
        sa.Column("clay", sa.Float(), nullable=True),
        sa.Column("silt", sa.Float(), nullable=True),
        sa.Column("sand", sa.Float(), nullable=True),
        sa.Column("texture", sa.String(length=50), nullable=True),
        sa.Column("ph_status", sa.String(length=50), nullable=True),
        sa.Column("organic_matter_rating", sa.String(length=50), nullable=True),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_soil_analyses_analyzed_at"), ["analyzed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_soil_analyses_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soil_analyses_id"))
        batch_op.drop_index(batch_op.f("ix_soil_analyses_analyzed_at"))

    op.drop_table("soil_analyses")
    with op.batch_alter_table("scenario_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_runs_run_at"))
        batch_op.drop_index(batch_op.f("ix_scenario_runs_id"))

    op.drop_table("scenario_runs")
    with op.batch_alter_table("satellite_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_satellite_analyses_id"))
        batch_op.drop_index(batch_op.f("ix_satellite_analyses_analyzed_at"))

    op.drop_table("satellite_analyses")
    with op.batch_alter_table("eco_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eco_transactions_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_eco_transactions_timestamp"))
        batch_op.drop_index(batch_op.f("ix_eco_transactions_id"))

    op.drop_table("eco_transactions")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_id"))
        batch_op.drop_index(batch_op.f("ix_products_category"))

    op.drop_table("products")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_token"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_id"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farms_id"))

    op.drop_table("farms")
    with op.batch_alter_table("eco_wallets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eco_wallets_id"))

    op.drop_table("eco_wallets")
    with op.batch_alter_table("carbon_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_carbon_projects_id"))

    op.drop_table("carbon_projects")
    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_conversations_id"))
        batch_op.drop_index(batch_op.f("ix_ai_conversations_asked_at"))

    op.drop_table("ai_conversations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("soil_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soil_profiles_name"))

    op.drop_table("soil_profiles")
    with op.batch_alter_table("recommendation_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_cache_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_cache_context_hash"))

    op.drop_table("recommendation_cache")
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plants_scientific_name"))

    op.drop_table("plants")
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_materials_name"))

    op.drop_table("materials")
    # ### end Alembic commands ###
