"""Phase 2: Legal texts and Tool Registry tables

Revision ID: p2_phase2_legal_tool_registry
Revises: 20260918_140000_village_hub_extended
Create Date: 2026-09-23 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "p2_phase2_legal_tool_registry"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_texts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="draft"),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("locale", "slug", "version", name="uq_legal_text_locale_slug_version"),
    )
    op.create_index("ix_legal_text_locale_slug_status", "legal_texts", ["locale", "slug", "status"])

    op.create_table(
        "tool_registry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tool_id", sa.String(length=32), nullable=False),
        sa.Column("name_fa", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("fidelity", sa.String(length=20), nullable=True),
        sa.Column("reference", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("service_slug", sa.String(length=100), nullable=True),
        sa.Column("endpoint_path", sa.String(length=200), nullable=True),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_id"),
    )
    op.create_index("ix_tool_registry_domain_category", "tool_registry", ["domain", "category"])
    op.create_index("ix_tool_registry_service_slug", "tool_registry", ["service_slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_registry_service_slug", table_name="tool_registry")
    op.drop_index("ix_tool_registry_domain_category", table_name="tool_registry")
    op.drop_table("tool_registry")
    op.drop_index("ix_legal_text_locale_slug_status", table_name="legal_texts")
    op.drop_table("legal_texts")
    # ### end Alembic commands ###
