import { Download, FileText, FileSpreadsheet, FileJson2 } from 'lucide-react';
import { useLang } from '../../i18n/LanguageContext';
import Reveal from '../ui/Reveal';
import type { Lang } from '../../content/site';

interface ReportFormat {
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  format: 'csv' | 'json' | 'pdf';
  note: string;
}

export default function ImpactReportBox() {
  const { t, lang } = useLang();

  const formats: ReportFormat[] = [
    { label: 'CSV', icon: FileSpreadsheet, format: 'csv', note: lang === 'fa' ? 'داده‌های خام متریک' : 'Raw metric data' },
    { label: 'JSON', icon: FileJson2, format: 'json', note: lang === 'fa' ? 'داده‌های ساختاری' : 'Structured data' },
    { label: 'PDF', icon: FileText, format: 'pdf', note: lang === 'fa' ? 'خلاصه کارشناسی' : 'Executive summary' },
  ];

  const buildReportData = () => ({
    exportedAt: new Date().toISOString(),
    lang,
    brand: t.brand.name,
    metrics: t.impact.metrics.map((m) => ({ name: m.name, unit: m.unit, desc: m.desc, source: m.source, standard: m.standard })),
    projects: t.impact.projects,
    timeSeries: t.impact.sampleTimeSeries,
  });

  const downloadAs = (format: 'csv' | 'json' | 'pdf') => {
    const data = buildReportData();

    if (format === 'csv') {
      const headers = ['name', 'unit', 'desc', 'source', 'standard'];
      const rows = data.metrics.map((m) => headers.map((h) => `"${m[h as keyof typeof m] ?? ''}"`).join(','));
      const csv = [headers.join(','), ...rows].join('\n');
      triggerDownload(csv, 'text/csv', `eco-nojin-impact-${lang}.csv`);
    } else if (format === 'json') {
      triggerDownload(JSON.stringify(data, null, 2), 'application/json', `eco-nojin-impact-${lang}.json`);
    } else if (format === 'pdf') {
      printReport(data, lang);
    }
  };

  return (
    <section className="px-4 py-12 sm:px-6">
      <Reveal className="mx-auto flex max-w-4xl flex-col gap-6">
        <div className="text-center">
          <h2 className="text-2xl font-extrabold text-[var(--color-night-100)] sm:text-3xl">{t.impact.reportTitle}</h2>
          <p className="mt-2 max-w-2xl text-sm leading-7 text-[var(--color-night-200)]/60">{t.impact.reportNote}</p>
        </div>

        <div className="glass rounded-3xl p-6">
          <div className="flex flex-col gap-3 sm:flex-row sm:gap-4">
            {formats.map((fmt) => {
              const Icon = fmt.icon;
              return (
                <button key={fmt.format} type="button" onClick={() => downloadAs(fmt.format)} className="glass glass-hover flex flex-1 items-center justify-center gap-2 rounded-2xl py-4 text-center transition-all">
                  <Icon className="h-5 w-5 text-[var(--color-aqua-500)]" />
                  <span className="text-sm font-bold text-[var(--color-night-100)]">{fmt.label}</span>
                  <span className="mt-1 text-[10px] text-[var(--color-night-200)]/40">{fmt.note}</span>
                </button>
              );
            })}
          </div>
          <p className="mt-4 flex items-center gap-1 text-[10px] text-[var(--color-night-200)]/35">
            <Download className="h-3 w-3" />
            {lang === 'fa' ? 'خروجی شامل تمام متریک‌ها، پروژه‌ها و داده‌های نمونه است.' : 'Export includes all metrics, projects, and sample data.'}
          </p>
        </div>
      </Reveal>
    </section>
  );
}

function triggerDownload(content: string, mime: string, filename: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function printReport(data: Record<string, unknown>, lang: Lang) {
  const metrics = (data.metrics as Array<Record<string, string>>) ?? [];
  const rows = metrics.map((m) => `<tr><td>${escapeHtml(m.name)}</td><td>${escapeHtml(m.unit)}</td><td>${escapeHtml(m.desc)}</td><td>${escapeHtml(m.source)}</td><td>${escapeHtml(m.standard)}</td></tr>`).join('');
  const html = `<!DOCTYPE html><html lang="${lang}"><head><meta charset="UTF-8"><title>Eco Nojin Impact Report</title>
<style>body{font-family:system-ui,sans-serif;margin:2rem;color:#1a1510}h1{color:#2fb36b}table{border-collapse:collapse;width:100%;margin-top:1rem}th,td{border:1px solid #ccc;padding:0.5rem;text-align:left;font-size:12px}th{background:#f0f0f0}</style></head>
<body>
<h1>Eco Nojin — ${lang === 'fa' ? 'گزارش تأثیر' : 'Impact Report'}</h1>
<p><strong>Date:</strong> ${data.exportedAt} &nbsp;|&nbsp; <strong>Brand:</strong> ${data.brand}</p>
<h2>${lang === 'fa' ? 'متریک‌ها' : 'Metrics'}</h2>
<table><thead><tr><th>Name</th><th>Unit</th><th>Description</th><th>Source</th><th>Standard</th></tr></thead><tbody>${rows}</tbody></table>
<p style="margin-top:2rem;font-size:11px;color:#888">Generated by Eco Nojin platform.</p>
</body></html>`;
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
  setTimeout(() => w.print(), 300);
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] ?? c));
}