"""R18 baseline: recorded engine outputs for change attribution.

Why this exists
---------------
Phase 3 of the integration plan changes equations in the engine. Those changes
move numbers that other modules consume. Without a recorded "before", an
intended correction and an accidental side effect look identical, which is the
failure mode Decision 7 exists to prevent — applied to code instead of finance.

This package holds no expected values of its own. ``R18.json`` is generated by
running the engine, so it can never be satisfied by a number written by hand
from engine output. The *value* of the baseline is that it changes loudly and
attributably, not that it is authoritative.

Commands
--------
    python -m engine.baseline.capture --show        # print the live capture
    python -m engine.baseline.capture --diff        # compare against R18.json
    python -m engine.baseline.capture --regenerate  # rewrite R18.json

Rules
-----
1. ``--regenerate`` is a separate verb, not a flag on ``--diff``, so a
   stale-baseline failure can never quietly rewrite itself.
2. A regenerated baseline must name the governing standard in its commit
   message, matching the project rule that references cite a chapter and table
   rather than a line number.
3. Removing a case is a decision, not a cleanup. It removes the ability to
   attribute a future change to whatever that case was witnessing.
"""
