// AUTO-GENERATED by scripts/generate_pages.py (Phase 3) — do not edit by hand.
export interface SiteSectionData { h?: string; p: string[]; b: string[]; }
export interface PageContentData {
  title: string;
  description: string;
  badge: string;
  sections: SiteSectionData[];
  related: string[];
}
export const pageContent: Record<string, PageContentData> = {
 "services": {
  "title": "خدمات اکو نوژین",
  "description": "مجموعه کامل خدمات دانش‌بنیان برای کشاورزی اقلیم‌هوشمند، آب، خاک و کربن — از مشاوره تا بازار.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "مشاوره علمی",
    "p": [
     "مشاوره کشاورزی بر پایه منابع علمی (FAO و همکاران) با موتور بازیابی دانش و مدل‌های محلی — بدون هزینه و بدون نیاز به اینترنت پرسرعت."
    ],
    "b": [
     "پاسخ با ذکر منبع و درصد ارتباط",
     "پشتیبانی ۱۴ زبان",
     "در دسترس از ربات‌های تلگرام، ایتا و وب"
    ]
   },
   {
    "h": "پایش و مدل‌سازی",
    "p": [
     "پایش مزرعه با داده ماهواره‌ای، مدل‌سازی آب و خاک با موتور HyDroMa و سناریوسازی اقلیمی."
    ],
    "b": [
     "پایش پوشش گیاهی و رطوبت",
     "مدل‌های ریچاردز، سن‌ونان و FAO-56",
     "پیش‌بینی سناریوهای خشک‌سالی"
    ]
   },
   {
    "h": "اقتصاد سبز",
    "p": [
     "بازار محصولات، کیف پول اکو و مسیر آینده اعتبار کربن با روش‌شناسی معتبر (VM0042) پس از اخذ مجوز قانونی."
    ],
    "b": [
     "بازار کشاورزان",
     "کیف پول اکو",
     "اعتبار کربن — پس از مشاوره حقوقی"
    ]
   }
  ],
  "related": [
   "tools",
   "science",
   "learn/soil",
   "modules/ai"
  ]
 },
 "services/advisory": {
  "title": "خدمت مشاوره علمی",
  "description": "دستیار دانش‌بنیان کشاورزی: سؤال بپرسید، پاسخ مستند بگیرید.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "چطور کار می‌کند؟",
    "p": [
     "سؤال شما با موتور بازیابی دانش به مرتبط‌ترین اسناد علمی (کمپوست، آبیاری، خاک، آفات) متصل می‌شود و پاسخ با استناد ساخته می‌شود — هیچ محتوایی از حافظه مدل اختراع نمی‌شود."
    ],
    "b": [
     "بازیابی سه سند مرتبط",
     "پاسخ به زبان کاربر (در صورت روشن بودن مدل محلی)",
     "فهرست منابع و درصد ارتباط"
    ]
   },
   {
    "h": "کانال‌ها",
    "p": [],
    "b": [
     "وب‌اپ",
     "ربات تلگرام",
     "ربات ایتا",
     "پیام‌کوتاه و صدا (در نقشه راه)"
    ]
   }
  ],
  "related": [
   "learn",
   "services/education",
   "tools/irrigation",
   "modules/ai"
  ]
 },
 "services/monitoring": {
  "title": "خدمت پایش مزرعه",
  "description": "پایش ماهواره‌ای پوشش گیاهی، رطوبت و تنش — با داده واقعی از فاز ۴.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "چه چیزی پایش می‌شود؟",
    "p": [],
    "b": [
     "شاخص پوشش گیاهی (NDVI)",
     "رطوبت خاک",
     "تنش آبی و توصیه آبیاری",
     "هشدارهای هوشمند (موتور هشدار فاز ۲)"
    ]
   },
   {
    "h": "وضعیت صادقانه داده",
    "p": [
     "در نسخه فعلی داده ماهواره شبیه‌سازی شده است (نقص W-001 ثبت شده). از فاز ۴، خط لوله کوپرنیکوس داده واقعی را جایگزین می‌کند."
    ],
    "b": [
     "هیچ هشداری بدون داده واقعی صادر نمی‌شود",
     "برچسب منبع داده روی هر خروجی"
    ]
   }
  ],
  "related": [
   "modules/satellite",
   "modules/analytics",
   "dashboard/alerts",
   "science/datasets"
  ]
 },
 "services/carbon": {
  "title": "خدمت کربن و اقلیم",
  "description": "مسیر ترسیب کربن خاک و گزارش‌دهی اقلیمی برای کشاورزی.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "چه کاری انجام می‌دهد",
    "p": [],
    "b": [
     "برآورد ذخیره کربن خاک با فرمول IPCC",
     "ردپای کربن مزرعه",
     "آموزش کشاورزی کربنی"
    ]
   },
   {
    "h": "نکته حقوقی",
    "p": [
     "بر اساس قوانین ایران (بازار رمزارز از بهمن ۱۴۰۳ محدود شده)، هر توکن زیست‌محیطی تنها پس از مشاوره حقوقی و اخذ مجوز عرضه می‌شود.",
     "روش‌شناسی هدف: VM0042 با راستی‌آزمایی مستقل."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/carbon",
   "tools/carbon-stock",
   "tools/co2-offset",
   "science/publications"
  ]
 },
 "services/education": {
  "title": "خدمت آموزش",
  "description": "یادگیری گام‌به‌گام با امتیاز و سطح‌بندی — دانش علمی در قالب تجربه.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "ویژگی‌ها",
    "p": [],
    "b": [
     "۴+ ماژول آموزشی فعال",
     "سیستم امتیاز و سطح (گیمیفیکیشن)",
     "پیشرفت ذخیره‌شده در مرورگر",
     "آزمون‌ها و نشان‌ها (به‌زودی)"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/compost",
   "learn/irrigation/scheduling",
   "modules/ecowallet"
  ]
 },
 "services/marketplace": {
  "title": "خدمت بازار کشاورزان",
  "description": "بازار محصولات و نهاده‌ها — کشاورز به کشاورز.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "ثبت محصول و نهاده",
     "جستجو و فیلتر",
     "ارتباط مستقیم خریدار و فروشنده",
     "امتیاز اعتماد"
    ]
   }
  ],
  "related": [
   "modules/marketplace",
   "dashboard/marketplace",
   "account/wallet",
   "services/wallet"
  ]
 },
 "services/wallet": {
  "title": "کیف پول اکو",
  "description": "مدیریت امتیازها و تراکنش‌های اکو در اکوسیستم پلتفرم.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "موجودی اکو و تاریخچه تراکنش",
     "پاداش یادگیری و مشارکت",
     "اتصال به بازار در فاز ۸ (پس از بررسی قانونی)"
    ]
   }
  ],
  "related": [
   "modules/ecowallet",
   "dashboard/wallet",
   "services/marketplace",
   "learn"
  ]
 },
 "services/api": {
  "title": "API برای توسعه‌دهندگان",
  "description": "دسترسی برنامه‌نویسی به موتور مدل‌سازی و دانش اکو نوژین.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "مستندات OpenAPI (FastAPI)",
     "مدل‌های آب و خاک",
     "موتور بازیابی دانش",
     "احراز هویت API در فاز ۵"
    ]
   }
  ],
  "related": [
   "science/models",
   "science/open-data",
   "admin/docs",
   "science/research"
  ]
 },
 "services/consulting": {
  "title": "مشاوره تخصصی",
  "description": "اتصال کشاورز به کارشناسان و مراکز ترویج.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "مسیرها",
    "p": [],
    "b": [
     "درخواست مشاوره",
     "کارشناسان ترویج",
     "همکاری با دانشگاه‌ها (فاز ۱۰)"
    ]
   }
  ],
  "related": [
   "services/advisory",
   "community",
   "support",
   "contact"
  ]
 },
 "services/training": {
  "title": "دوره‌های آموزشی",
  "description": "دوره‌های کوتاه علمی برای کشاورزان و دانشجویان.",
  "badge": "خدمات",
  "sections": [
   {
    "h": "دوره‌های پیشنهادی",
    "p": [],
    "b": [
     "کمپوست و کود آلی",
     "آبیاری قطره‌ای",
     "مدیریت تلفیقی آفات",
     "کربن خاک و اقلیم"
    ]
   }
  ],
  "related": [
   "services/education",
   "events",
   "webinars",
   "learn"
  ]
 },
 "partners": {
  "title": "همکاران",
  "description": "همکاری با دانشگاه‌ها، مراکز ترویج و سازمان‌های زیست‌محیطی.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "فرصت‌های همکاری",
    "p": [],
    "b": [
     "دانشگاه‌ها و مراکز پژوهشی (فاز ۱۰: پایلوت ۳ روستا)",
     "سازمان‌های جهاد کشاورزی",
     "شرکت‌های فناوری آب و خاک",
     "سازمان‌های مردم‌نهاد زیست‌محیطی"
    ]
   }
  ],
  "related": [
   "about",
   "roadmap",
   "science/labs",
   "news/partnership"
  ]
 },
 "roadmap": {
  "title": "نقشه راه",
  "description": "برنامه ۱۱ فازی اکو نوژین — از پایه امنیت تا مقیاس و عملیات میدانی.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "فازهای کلیدی",
    "p": [],
    "b": [
     "فاز ۰–۲: پایه، ربات‌ها — انجام شد",
     "فاز ۳: فرانت‌اند کاربر — در جریان",
     "فاز ۴: داده واقعی کوپرنیکوس",
     "فاز ۵–۶: پنل مدیریت و محتوا",
     "فاز ۷: کتابخانه ۲۲ مدل + PINN",
     "فاز ۸: اقتصاد توکن (پس از مجوز)",
     "فاز ۹: لایه آکادمیک و انتشار داده",
     "فاز ۱۰: عملیات پیشرفته و پایلوت میدانی"
    ]
   }
  ],
  "related": [
   "science/research",
   "science/field-pilot",
   "admin/backup",
   "partners"
  ]
 },
 "careers": {
  "title": "همکاری با ما",
  "description": "اکو نوژین با کار تیمی بدون نیروی فنی تمام‌وقت ساخته می‌شود — مشارکت موضوعی و میدانی بپذیریم.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "زمینه‌های مشارکت",
    "p": [],
    "b": [
     "کارشناسان کشاورزی و خاک",
     "مربیان ترویج",
     "دانشجویان پژوهشگر (کارآموزی)",
     "داوطلبان ترجمه ۱۴ زبان"
    ]
   }
  ],
  "related": [
   "partners",
   "contact",
   "mission",
   "about"
  ]
 },
 "press": {
  "title": "رسانه",
  "description": "اخبار، بیانیه‌ها و معرفی پلتفرم برای رسانه‌ها.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "بسته رسانه‌ای",
    "p": [],
    "b": [
     "معرفی پروژه اکو نوژین",
     "لوگو و هویت بصری",
     "ارتباط با رسانه‌ها"
    ]
   }
  ],
  "related": [
   "news",
   "news/launch",
   "news/partnership",
   "contact"
  ]
 },
 "newsletter": {
  "title": "خبرنامه",
  "description": "خلاصه هفتگی اخبار علمی و به‌روزرسانی‌های پلتفرم.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "محتوای خبرنامه",
    "p": [],
    "b": [
     "نکات علمی فصل",
     "به‌روزرسانی فازها",
     "رویدادها و وبینارها",
     "فرصت‌های مشارکت"
    ]
   }
  ],
  "related": [
   "blog",
   "news",
   "community",
   "support"
  ]
 },
 "events": {
  "title": "رویدادها",
  "description": "کارگاه‌ها و رویدادهای حضوری و آنلاین.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "رویدادها",
    "p": [],
    "b": [
     "کارگاه کمپوست روستایی",
     "وبینار آبیاری قطره‌ای",
     "همایش کربن خاک (برنامه‌ریزی)"
    ]
   }
  ],
  "related": [
   "webinars",
   "community",
   "partners",
   "news"
  ]
 },
 "webinars": {
  "title": "وبینارها",
  "description": "جلسات آنلاین آموزشی با کارشناسان.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "موضوعات",
    "p": [],
    "b": [
     "FAO-56 و نیاز آبی",
     "سلامت خاک",
     "مدیریت تلفیقی آفات",
     "اقتصاد کربن"
    ]
   }
  ],
  "related": [
   "events",
   "services/education",
   "learn",
   "community"
  ]
 },
 "blog": {
  "title": "وبلاگ",
  "description": "نوشته‌های علمی-کاربردی درباره خاک، آب، اقلیم و کشاورزی.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "دسته‌ها",
    "p": [],
    "b": [
     "سلامت خاک",
     "بحران آب",
     "کشاورزی کربنی",
     "سازگاری با اقلیم"
    ]
   }
  ],
  "related": [
   "blog/soil-health",
   "blog/water-scarcity",
   "blog/carbon-farming",
   "blog/climate-adaptation"
  ]
 },
 "blog/soil-health": {
  "title": "سلامت خاک: چرا مهم است؟",
  "description": "خاک سالم، غذای سالم — مرور شاخص‌های کلیدی سلامت خاک.",
  "badge": "وبلاگ",
  "sections": [
   {
    "h": "شاخص‌های سلامت خاک",
    "p": [],
    "b": [
     "ماده آلی",
     "pH و عناصر غذایی",
     "بافت و ساختمان خاک",
     "فعالیت زیستی (کرم‌های خاکی و میکروب‌ها)"
    ]
   },
   {
    "h": "چرا اکنون؟",
    "p": [
     "فرسایش و فشردگی خاک در ایران جدی است؛ پایش و اصلاح به‌موقع هزینه را به‌شدت کاهش می‌دهد."
    ],
    "b": []
   }
  ],
  "related": [
   "blog",
   "learn/soil",
   "tools/carbon-stock",
   "learn/soil/organic-matter"
  ]
 },
 "blog/water-scarcity": {
  "title": "بحران آب و کشاورزی",
  "description": "چگونه با مدیریت صحیح آبیاری، بحران آب را مهار کنیم؟",
  "badge": "وبلاگ",
  "sections": [
   {
    "h": "راهکارها",
    "p": [],
    "b": [
     "آبیاری قطره‌ای و کم‌فشار",
     "زمان‌بندی آبیاری بر پایه نیاز واقعی گیاه",
     "کاهش تبخیر با مالچ",
     "انتخاب ارقام مقاوم به خشکی"
    ]
   }
  ],
  "related": [
   "blog",
   "learn/water",
   "tools/irrigation",
   "learn/irrigation/scheduling"
  ]
 },
 "blog/carbon-farming": {
  "title": "کشاورزی کربنی",
  "description": "ترسیب کربن در خاک به‌عنوان راهکار اقلیمی و درآمد نو.",
  "badge": "وبلاگ",
  "sections": [
   {
    "h": "روش‌های ترسیب",
    "p": [],
    "b": [
     "کود سبز و پوشش گیاهی",
     "کم‌خاک‌ورزی",
     "کمپوست و بیوچار",
     "مرتع‌داری پایدار"
    ]
   }
  ],
  "related": [
   "blog",
   "services/carbon",
   "tools/carbon-stock",
   "science/publications"
  ]
 },
 "blog/climate-adaptation": {
  "title": "سازگاری با تغییر اقلیم",
  "description": "اقدامات عملی برای مزرعه‌ای مقاوم در برابر اقلیم متغیر.",
  "badge": "وبلاگ",
  "sections": [
   {
    "h": "اقدامات",
    "p": [],
    "b": [
     "تنوع ارقام",
     "مدیریت ریسک بارش",
     "سامانه‌های هشدار",
     "بیمه محصولات (توصیه)"
    ]
   }
  ],
  "related": [
   "blog",
   "learn/climate",
   "modules/scenarios",
   "science/research"
  ]
 },
 "news": {
  "title": "اخبار",
  "description": "به‌روزرسانی‌ها و دستاوردهای پلتفرم اکو نوژین.",
  "badge": "سازمان",
  "sections": [
   {
    "h": "تازه‌ها",
    "p": [],
    "b": [
     "فاز ۰ تا ۲ تکمیل شد",
     "فاز ۳ فرانت‌اند در جریان",
     "ربات تلگرام و ایتا آماده"
    ]
   }
  ],
  "related": [
   "press",
   "blog",
   "events",
   "roadmap"
  ]
 },
 "news/launch": {
  "title": "رونمایی فاز ۳",
  "description": "فرانت‌اند کاربر با بیش از ۱۵۰ صفحه فعال رونمایی شد.",
  "badge": "اخبار",
  "sections": [
   {
    "h": "جزئیات",
    "p": [],
    "b": [
     "۱۵۰+ صفحه فعال",
     "۱۲ ماشین‌حساب تخصصی",
     "گیمیفیکیشن آموزشی",
     "طراحی ریسپانسیو و راست‌چین"
    ]
   }
  ],
  "related": [
   "news",
   "roadmap",
   "services",
   "blog"
  ]
 },
 "news/partnership": {
  "title": "همکاری دانشگاهی",
  "description": "برنامه پایلوت میدانی با دانشگاه‌ها — سه روستا (فاز ۱۰).",
  "badge": "اخبار",
  "sections": [
   {
    "h": "اهداف پایلوت",
    "p": [],
    "b": [
     "اعتبارسنجی مدل‌ها در مزرعه",
     "جمع‌آوری داده واقعی خاک و آب",
     "آموزش کشاورزان"
    ]
   }
  ],
  "related": [
   "news",
   "partners",
   "science/field-pilot",
   "science/labs"
  ]
 },
 "faq": {
  "title": "پرسش‌های پرتکرار",
  "description": "پاسخ به پرسش‌های رایج درباره پلتفرم.",
  "badge": "پشتیبانی",
  "sections": [
   {
    "h": "عمومی",
    "p": [],
    "b": [
     "اکو نوژین چیست؟",
     "هزینه استفاده چقدر است؟",
     "به چه زبانی‌هایی پاسخ می‌دهد؟",
     "داده‌های من چطور محافظت می‌شود؟"
    ]
   },
   {
    "h": "فنی",
    "p": [],
    "b": [
     "آیا به اینترنت پرسرعت نیاز است؟",
     "چطور از ربات تلگرام استفاده کنم؟",
     "داده ماهواره چه زمانی واقعی می‌شود؟"
    ]
   }
  ],
  "related": [
   "help",
   "support",
   "services",
   "community"
  ]
 },
 "help": {
  "title": "راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از سرویس‌ها.",
  "badge": "پشتیبانی",
  "sections": [
   {
    "h": "راهنماها",
    "p": [],
    "b": [
     "شروع کار با ربات",
     "ثبت مزرعه",
     "پرسش از کارشناس",
     "استفاده از ماشین‌حساب‌ها"
    ]
   }
  ],
  "related": [
   "faq",
   "support",
   "services/education",
   "learn"
  ]
 },
 "support": {
  "title": "پشتیبانی",
  "description": "مسیرهای ارتباط با تیم پشتیبانی.",
  "badge": "پشتیبانی",
  "sections": [
   {
    "h": "مسیرها",
    "p": [],
    "b": [
     "ربات تلگرام",
     "فرم تماس",
     "انجمن کاربران",
     "ایمیل پشتیبانی"
    ]
   }
  ],
  "related": [
   "faq",
   "help",
   "contact",
   "community"
  ]
 },
 "community": {
  "title": "جامعه کاربران",
  "description": "فضای تبادل تجربه کشاورزان، دانشجویان و کارشناسان.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "ارزش‌ها",
    "p": [],
    "b": [
     "احترام و همدلی",
     "دانش مبتنی بر شواهد",
     "ممنوعیت تبلیغات فریبنده",
     "همیاری محلی"
    ]
   }
  ],
  "related": [
   "forum",
   "events",
   "webinars",
   "community/guidelines"
  ]
 },
 "community/guidelines": {
  "title": "قوانین جامعه",
  "description": "چارچوب رفتاری برای گفتگوی سالم در انجمن‌ها.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "اصول",
    "p": [],
    "b": [
     "بدون توهین و تبعیض",
     "بدون ادعای درمان یا محصولات جعلی",
     "استناد به منابع علمی",
     "گزارش تخلف به پشتیبانی"
    ]
   }
  ],
  "related": [
   "community",
   "forum",
   "support",
   "legal/terms"
  ]
 },
 "forum": {
  "title": "انجمن گفتگو",
  "description": "پرسش و پاسخ کاربران درباره خاک، آب، آفات و مدیریت مزرعه.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "انجمن‌ها",
    "p": [],
    "b": [
     "خاک و تغذیه",
     "آب و آبیاری",
     "کربن و اقلیم",
     "آفات و بیماری‌ها"
    ]
   }
  ],
  "related": [
   "community",
   "forum/soil",
   "forum/water",
   "forum/carbon"
  ]
 },
 "forum/soil": {
  "title": "انجمن خاک",
  "description": "بحث درباره سلامت خاک، کود و اصلاح خاک.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "موضوعات داغ",
    "p": [],
    "b": [
     "نتیجه آزمون خاک",
     "کود آلی در برابر شیمیایی",
     "اصلاح خاک شور"
    ]
   }
  ],
  "related": [
   "forum",
   "learn/soil",
   "tools/lime",
   "tools/fertilizer"
  ]
 },
 "forum/water": {
  "title": "انجمن آب",
  "description": "مدیریت آب کشاورزی و آبیاری.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "موضوعات داغ",
    "p": [],
    "b": [
     "زمان‌بندی آبیاری",
     "قطره‌ای در برابر غرقابی",
     "هدررفت آب و راهکارها"
    ]
   }
  ],
  "related": [
   "forum",
   "learn/water",
   "tools/irrigation",
   "blog/water-scarcity"
  ]
 },
 "forum/carbon": {
  "title": "انجمن کربن",
  "description": "ترسیب کربن، کمپوست و اقتصاد سبز.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "موضوعات داغ",
    "p": [],
    "b": [
     "کمپوست خانگی و مزرعه‌ای",
     "بیوچار",
     "بازار اعتبار کربن (با ملاحظات قانونی)"
    ]
   }
  ],
  "related": [
   "forum",
   "services/carbon",
   "learn/carbon",
   "tools/compost-cn"
  ]
 },
 "forum/irrigation": {
  "title": "انجمن آبیاری",
  "description": "طراحی و نگهداری سامانه‌های آبیاری.",
  "badge": "جامعه",
  "sections": [
   {
    "h": "موضوعات داغ",
    "p": [],
    "b": [
     "طراحی قطره‌ای",
     "فیلتر و گرفتگی",
     "آبیاری هوشمند"
    ]
   }
  ],
  "related": [
   "forum",
   "learn/irrigation",
   "tools/drip-design",
   "tools/irrigation"
  ]
 },
 "science": {
  "title": "مرکز علم",
  "description": "پنجره باز علم: مدل‌ها، داده‌ها، انتشارات و بازتولیدپذیری.",
  "badge": "علم",
  "sections": [
   {
    "h": "ارکان",
    "p": [],
    "b": [
     "مدل‌های با کارت مدل (Model Cards)",
     "داده‌های با DOI و انتشار در Zenodo (فاز ۹)",
     "استناد خودکار در پاسخ‌ها (فاز ۹)",
     "پایلوت میدانی با دانشگاه‌ها (فاز ۱۰)"
    ]
   }
  ],
  "related": [
   "science/research",
   "science/models",
   "science/datasets",
   "science/open-data"
  ]
 },
 "science/research": {
  "title": "پژوهش",
  "description": "پروژه‌های پژوهشی پلتفرم و مسیر همکاری علمی.",
  "badge": "علم",
  "sections": [
   {
    "h": "محورها",
    "p": [],
    "b": [
     "مدل‌سازی هیدرولوژی و خاک",
     "شبکه‌های عصبی PINN برای شبیه‌سازهای سریع",
     "پایش ماهواره‌ای",
     "ارزیابی خدمات اکوسیستمی"
    ]
   },
   {
    "h": "بازتولیدپذیری",
    "p": [
     "هر پژوهش با کد، داده و محیط نسخه‌بندی‌شده (DVC + MLflow از فاز ۴) منتشر می‌شود — اصل «بدون بازتولید، بدون ادعا»."
    ],
    "b": []
   }
  ],
  "related": [
   "science",
   "science/labs",
   "science/field-pilot",
   "partners"
  ]
 },
 "science/datasets": {
  "title": "مجموعه‌داده‌ها",
  "description": "کاتالوگ داده‌های باز پلتفرم.",
  "badge": "علم",
  "sections": [
   {
    "h": "داده‌ها",
    "p": [],
    "b": [
     "داده کوپرنیکوس (فاز ۴)",
     "آزمون‌های خاک نمونه",
     "داده هواشناسی ERA5",
     "داده پایلوت میدانی (فاز ۱۰)"
    ]
   },
   {
    "h": "قواعد",
    "p": [
     "هر مجموعه داده با کارت داده، مجوز و DOI منتشر می‌شود (فاز ۹)."
    ],
    "b": []
   }
  ],
  "related": [
   "science",
   "science/open-data",
   "modules/satellite",
   "admin/data"
  ]
 },
 "science/models": {
  "title": "کتابخانه مدل‌ها",
  "description": "مدل‌های علمی قابل اجرا — از ریچاردز تا یادگیری ماشین.",
  "badge": "علم",
  "sections": [
   {
    "h": "مدل‌های اصلی",
    "p": [],
    "b": [
     "ریچاردز ۱D (رطوبت خاک)",
     "سن‌ونان ۱D (رواناب)",
     "FAO-56 (نیاز آبی)",
     "RUSLE (فرسایش)",
     "آکواکراپ (عملکرد)",
     "PINN (جایگزین سریع — فاز ۷)"
    ]
   },
   {
    "h": "کارت مدل",
    "p": [
     "هر مدل با کارت مدل (ورودی، محدودیت، اعتبارسنجی) مستند می‌شود."
    ],
    "b": []
   }
  ],
  "related": [
   "science",
   "modules/scenarios",
   "modules/analytics",
   "services/api"
  ]
 },
 "science/publications": {
  "title": "انتشارات",
  "description": "مقالات و گزارش‌های علمی پلتفرم.",
  "badge": "علم",
  "sections": [
   {
    "h": "خروجی‌ها",
    "p": [],
    "b": [
     "گزارش‌های فنی فازها",
     "مقالات مروری (برنامه)",
     "مستندات روش‌شناسی"
    ]
   }
  ],
  "related": [
   "science",
   "science/citations",
   "science/research",
   "blog"
  ]
 },
 "science/citations": {
  "title": "استناد خودکار",
  "description": "پاسخ‌های هوشمند با ارجاع خودکار به OpenAlex، FAO و Crossref (فاز ۹).",
  "badge": "علم",
  "sections": [
   {
    "h": "چطور کار می‌کند",
    "p": [
     "پاسخ هر پرسش، منابع واقعی (شناسه DOI یا پایگاه) را کنار خود می‌آورد — نه ادعای بی‌سند."
    ],
    "b": []
   }
  ],
  "related": [
   "science",
   "science/publications",
   "modules/ai",
   "learn"
  ]
 },
 "science/open-data": {
  "title": "داده‌باز",
  "description": "تعهد به داده‌باز و علم باز.",
  "badge": "علم",
  "sections": [
   {
    "h": "اصول FAIR",
    "p": [],
    "b": [
     "قابل یافتن (Findable)",
     "قابل دسترس (Accessible)",
     "قابل تعامل (Interoperable)",
     "قابل استفاده مجدد (Reusable)"
    ]
   }
  ],
  "related": [
   "science",
   "science/datasets",
   "science/repositories",
   "legal/terms"
  ]
 },
 "science/repositories": {
  "title": "مخزن کد و داده",
  "description": "مخزن‌های عمومی پروژه.",
  "badge": "علم",
  "sections": [
   {
    "h": "مخزن‌ها",
    "p": [],
    "b": [
     "کد: گیت‌هاب سازمانی",
     "داده: Zenodo با DOI (فاز ۹)",
     "مستندات: در همین سامانه"
    ]
   }
  ],
  "related": [
   "science",
   "science/open-data",
   "science/datasets",
   "admin/docs"
  ]
 },
 "science/labs": {
  "title": "همکاری آزمایشگاهی",
  "description": "آزمایشگاه‌های خاک و آب شریک.",
  "badge": "علم",
  "sections": [
   {
    "h": "خدمات آزمایشگاهی",
    "p": [],
    "b": [
     "آزمون pH و EC",
     "ماده آلی",
     "بافت خاک",
     "کیفیت آب آبیاری"
    ]
   }
  ],
  "related": [
   "science",
   "partners",
   "science/field-pilot",
   "services/consulting"
  ]
 },
 "science/field-pilot": {
  "title": "پایلوت میدانی",
  "description": "برنامه سه‌روستا با دانشگاه‌ها — اعتبارسنجی در مزرعه واقعی (فاز ۱۰).",
  "badge": "علم",
  "sections": [
   {
    "h": "برنامه",
    "p": [],
    "b": [
     "انتخاب سه روستا با اقلیم‌های متفاوت",
     "نصب سنسورهای رطوبت و دما",
     "جمع‌آوری داده یک سال کامل",
     "مقایسه خروجی مدل با واقعیت"
    ]
   }
  ],
  "related": [
   "science",
   "partners",
   "science/labs",
   "roadmap"
  ]
 },
 "learn/soil": {
  "title": "آموزش: خاک",
  "description": "مفاهیم پایه خاک — بافت، pH، ماده آلی، شوری و سلامت خاک.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "بافت و ساختمان خاک",
     "pH و اصلاح آن",
     "ماده آلی و کمپوست",
     "شوری و مدیریت آن",
     "آزمون خاک"
    ]
   },
   {
    "h": "ابزار مرتبط",
    "p": [],
    "b": [
     "ماشین‌حساب آهک",
     "ماشین‌حساب کود",
     "ماشین‌حساب کربن"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/soil/ph",
   "learn/soil/organic-matter",
   "learn/soil/salinity"
  ]
 },
 "learn/water": {
  "title": "آموزش: آب",
  "description": "مدیریت آب کشاورزی — نیاز آبی، کیفیت و بهره‌وری.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "نیاز آبی گیاه",
     "کیفیت آب آبیاری",
     "ردپای آب",
     "مدیریت کم‌آبی"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/water/quality",
   "learn/water/management",
   "learn/irrigation"
  ]
 },
 "learn/climate": {
  "title": "آموزش: اقلیم",
  "description": "تغییر اقلیم، پیش‌بینی و سازگاری در مزرعه.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "گازهای گلخانه‌ای در کشاورزی",
     "سناریوهای اقلیمی",
     "سازگاری و کاهش ریسک",
     "پیش‌بینی بارش (GraphCast در پژوهش)"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/climate/greenhouse",
   "learn/climate/adaptation",
   "modules/scenarios"
  ]
 },
 "learn/carbon": {
  "title": "آموزش: کربن",
  "description": "چرخه کربن، ترسیب در خاک و گزارش‌دهی.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "چرخه کربن خاک",
     "روش‌های ترسیب",
     "حسابداری کربن",
     "بازار اعتبار کربن و ملاحظات قانونی"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/carbon/sequestration",
   "learn/carbon/accounting",
   "services/carbon"
  ]
 },
 "learn/crops": {
  "title": "آموزش: گیاهان زراعی",
  "description": "تغذیه گیاه، تناوب و انتخاب رقم.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "تناوب زراعی",
     "تغذیه و عناصر غذایی",
     "تراکم و بذر",
     "مدیریت بقایا"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/crops/rotation",
   "learn/crops/nutrition",
   "tools/seeding"
  ]
 },
 "learn/irrigation": {
  "title": "آموزش: آبیاری",
  "description": "روش‌ها و زمان‌بندی آبیاری مدرن.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "روش‌های آبیاری",
     "زمان‌بندی علمی",
     "طراحی قطره‌ای",
     "بهره‌وری آب"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/irrigation/drip",
   "learn/irrigation/scheduling",
   "tools/drip-design"
  ]
 },
 "learn/pests": {
  "title": "آموزش: آفات",
  "description": "مدیریت تلفیقی آفات (IPM) و کنترل زیستی.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "اصول IPM",
     "کنترل زیستی",
     "پایش آفات",
     "کاهش سم"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/pests/ipm",
   "learn/pests/biocontrol",
   "learn/ecology"
  ]
 },
 "learn/ecology": {
  "title": "آموزش: بوم‌شناسی",
  "description": "تنوع زیستی و خدمات اکوسیستم در مزرعه.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "تنوع زیستی مزرعه",
     "گرده‌افشان‌ها",
     "زیست‌بوم خاک",
     "کریدورهای اکولوژیک"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/ecology/biodiversity",
   "learn/pests/biocontrol",
   "blog/soil-health"
  ]
 },
 "learn/agronomy": {
  "title": "آموزش: زراعت",
  "description": "مدیریت زراعی — خاک‌ورزی، کاشت و داشت.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چه می‌آموزید؟",
    "p": [],
    "b": [
     "خاک‌ورزی حفاظتی",
     "کاشت و تراکم",
     "مدیریت داشت",
     "برداشت و پس از برداشت"
    ]
   }
  ],
  "related": [
   "learn",
   "learn/agronomy/tillage",
   "learn/crops",
   "tools/seeding"
  ]
 },
 "learn/compost": {
  "title": "آموزش: کمپوست",
  "description": "تولید کمپوست با کیفیت — از مواد اولیه تا محصول نهایی.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "گام‌ها",
    "p": [],
    "b": [
     "انتخاب مواد اولیه",
     "تنظیم نسبت C/N",
     "رطوبت و هوادهی",
     "رسیدگی و غربال"
    ]
   },
   {
    "h": "نکته کلیدی",
    "p": [
     "نسبت C/N بهینه بین ۲۵ تا ۳۵ است؛ کاه (۸۰) را با کود دامی (۲۰) حدود ۲ به ۱ مخلوط کنید."
    ],
    "b": []
   }
  ],
  "related": [
   "learn",
   "learn/soil/organic-matter",
   "tools/compost-cn",
   "blog/carbon-farming"
  ]
 },
 "learn/soil/ph": {
  "title": "مقاله: pH خاک",
  "description": "چرا pH خاک مهم است و چگونه آن را اصلاح کنیم؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مبانی",
    "p": [
     "pH خاک تعیین‌کننده دسترسی عناصر غذایی است: در خاک اسیدی، فسفر و مولیبدن کم‌دسترس‌ترند و آلومینیوم سمی می‌شود."
    ],
    "b": [
     "بازه مطلوب بیشتر گیاهان: ۶ تا ۷",
     "خاک‌های اسیدی (کمتر از ۶) با آهک اصلاح می‌شوند",
     "خاک‌های قلیایی با گوگرد و مواد آلی"
    ]
   },
   {
    "h": "اندازه‌گیری",
    "p": [
     "با دستگاه pH‌سنج یا کیت آزمون خاک؛ نمونه از عمق ریشه و چند نقطه مزرعه برداشته شود."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/soil",
   "tools/lime",
   "learn/soil/organic-matter",
   "forum/soil"
  ]
 },
 "learn/soil/organic-matter": {
  "title": "مقاله: ماده آلی خاک",
  "description": "ماده آلی — قلب سلامت خاک.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چرا حیاتی است؟",
    "p": [],
    "b": [
     "بهبود ساختمان و تهویه خاک",
     "افزایش ظرفیت نگهداشت آب",
     "منبع غذای میکروب‌ها",
     "ترسیب کربن"
    ]
   },
   {
    "h": "افزایش ماده آلی",
    "p": [
     "کمپوست، کود سبز، حفظ بقایا و کاهش خاک‌ورزی مسیرهای اصلی هستند — تغییر پایدار است و تدریجی."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/soil",
   "learn/compost",
   "tools/carbon-stock",
   "blog/soil-health"
  ]
 },
 "learn/soil/salinity": {
  "title": "مقاله: شوری خاک",
  "description": "شناخت و مدیریت خاک‌های شور.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "نشانه‌ها",
    "p": [],
    "b": [
     "پوسته سفید روی سطح",
     "سوختگی حاشیه برگ‌ها",
     "کاهش جوانه‌زنی",
     "EC بالای عصاره اشباع"
    ]
   },
   {
    "h": "مدیریت",
    "p": [
     "آبشویی با آب شیرین + زهکشی مناسب + ارقام مقاوم + مواد آلی — راهکار ترکیبی بهترین نتیجه را دارد."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/soil",
   "learn/water/quality",
   "forum/soil",
   "tools/irrigation"
  ]
 },
 "learn/soil/texture": {
  "title": "مقاله: بافت خاک",
  "description": "شن، سیلت و رس — چرا بافت مهم است؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مبانی",
    "p": [
     "بافت خاک تعیین‌کننده نگهداشت آب، تهویه و سهولت کار است: خاک رسی آب را نگه می‌دارد ولی زهکشی ضعیفی دارد؛ خاک شنی زهکشی خوب اما نگهداشت آب کم."
    ],
    "b": [
     "آزمون دستی (نوار) برای تخمین اولیه",
     "آزمون آزمایشگاهی (هیدرومتر) برای دقت",
     "اصلاح بافت با مواد آلی ممکن است، با شن و رس عملاً نه"
    ]
   }
  ],
  "related": [
   "learn/soil",
   "tools/soil-water",
   "learn/irrigation",
   "forum/soil"
  ]
 },
 "learn/water/quality": {
  "title": "مقاله: کیفیت آب آبیاری",
  "description": "EC، SAR و عناصر خطرناک در آب آبیاری.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "شاخص‌ها",
    "p": [],
    "b": [
     "EC: شوری کل",
     "SAR: نسبت سدیم — خطر سدیمی شدن خاک",
     "بور و کلر: سمی در غلظت بالا"
    ]
   },
   {
    "h": "توصیه",
    "p": [
     "آزمایش سالانه آب چاه/قنات؛ در SAR بالا از اصلاح‌کننده‌های کلسیمی و آبشویی دوره‌ای استفاده کنید."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/water",
   "learn/soil/salinity",
   "forum/water",
   "tools/irrigation"
  ]
 },
 "learn/water/management": {
  "title": "مقاله: مدیریت آب مزرعه",
  "description": "برنامه‌ریزی آبیاری در شرایط کم‌آبی.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "راهبردها",
    "p": [],
    "b": [
     "آبیاری ناقص (Deficit Irrigation) در مراحل غیرحساس",
     "مالچ برای کاهش تبخیر",
     "آبیاری شبانه",
     "انتخاب ارقام کوتاه‌دوره"
    ]
   }
  ],
  "related": [
   "learn/water",
   "tools/irrigation",
   "blog/water-scarcity",
   "modules/scenarios"
  ]
 },
 "learn/water/footprint": {
  "title": "مقاله: ردپای آب",
  "description": "هر محصول چقدر آب مصرف می‌کند؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مفهوم",
    "p": [
     "ردپای آب سبز (باران)، آبی (آبیاری) و خاکستری (آلودگی) را جدا می‌کنیم — شفافیت برای مصرف‌کننده و برنامه‌ریز."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/water",
   "tools/water-footprint",
   "blog/water-scarcity",
   "forum/water"
  ]
 },
 "learn/climate/greenhouse": {
  "title": "مقاله: گازهای گلخانه‌ای در کشاورزی",
  "description": "سهم کشاورزی از انتشار و راه‌های کاهش.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "منابع انتشار",
    "p": [],
    "b": [
     "کودهای نیتروژنه (N₂O)",
     "شالیکاری غرقابی (CH₄)",
     "سوخت ماشین‌آلات",
     "تغییر کاربری زمین"
    ]
   },
   {
    "h": "کاهش",
    "p": [
     "کوددهی دقیق، مدیریت آب شالیزار، خاک‌ورزی حفاظتی و انرژی تجدیدپذیر — هر کدام چند درصد انتشار را کم می‌کنند."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/climate",
   "services/carbon",
   "tools/co2-offset",
   "blog/carbon-farming"
  ]
 },
 "learn/climate/adaptation": {
  "title": "مقاله: سازگاری مزرعه با اقلیم",
  "description": "آماده‌سازی مزرعه برای اقلیم متغیر.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "اقدامات",
    "p": [],
    "b": [
     "تنوع ارقام و محصولات",
     "تقویم کاشت انعطاف‌پذیر",
     "سامانه هشدار یخ‌زدگی و گرما",
     "ذخیره آب و خاک‌پوش"
    ]
   }
  ],
  "related": [
   "learn/climate",
   "modules/scenarios",
   "blog/climate-adaptation",
   "science/research"
  ]
 },
 "learn/carbon/sequestration": {
  "title": "مقاله: ترسیب کربن در خاک",
  "description": "خاک‌ها چگونه کربن ذخیره می‌کنند؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مکانیزم",
    "p": [
     "گیاهان CO₂ را جذب و به صورت ماده آلی به خاک می‌دهند؛ مدیریت خوب، این کربن را در خاک نگه می‌دارد.",
     "ترسیب محدودیت دارد (اشباع) ولی مزایای جانبی فراوان: حاصلخیزی، نگهداشت آب، مقاومت به فرسایش."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/carbon",
   "tools/carbon-stock",
   "blog/carbon-farming",
   "learn/compost"
  ]
 },
 "learn/carbon/accounting": {
  "title": "مقاله: حسابداری کربن",
  "description": "اندازه‌گیری و گزارش کربن مزرعه.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "گام‌ها",
    "p": [],
    "b": [
     "تعیین مرز (مزرعه، دام، ماشین‌آلات)",
     "جمع‌آوری داده (سوخت، کود، عملکرد)",
     "محاسبه با ضرایب IPCC",
     "گزارش و راستی‌آزمایی"
    ]
   }
  ],
  "related": [
   "learn/carbon",
   "tools/co2-offset",
   "science/publications",
   "services/carbon"
  ]
 },
 "learn/crops/rotation": {
  "title": "مقاله: تناوب زراعی",
  "description": "چرا تناوب، زراعت را نجات می‌دهد؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مزایا",
    "p": [],
    "b": [
     "کاهش آفات و بیماری‌های تخصصی",
     "بهبود ساختمان خاک",
     "تثبیت نیتروژن با لگوم‌ها",
     "کاهش علف‌های هرز"
    ]
   }
  ],
  "related": [
   "learn/crops",
   "learn/agronomy",
   "learn/pests/ipm",
   "forum/soil"
  ]
 },
 "learn/crops/nutrition": {
  "title": "مقاله: تغذیه گیاه",
  "description": "عناصر پرمصرف و کم‌مصرف — زمان و روش مصرف.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "عناصر کلیدی",
    "p": [],
    "b": [
     "N (نیتروژن): رشد رویشی",
     "P (فسفر): ریشه و گل",
     "K (پتاسیم): مقاومت و کیفیت",
     "ریزمغذی‌ها: آهن، روی، بور"
    ]
   },
   {
    "h": "اصل طلایی",
    "p": [
     "کود بر اساس آزمون خاک، نه عادت — مصرف بی‌رویه هم هزینه دارد هم آلودگی."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/crops",
   "tools/fertilizer",
   "forum/soil",
   "learn/soil/ph"
  ]
 },
 "learn/irrigation/drip": {
  "title": "مقاله: آبیاری قطره‌ای",
  "description": "مزایا، اجزا و اشتباهات رایج.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مزایا",
    "p": [],
    "b": [
     "بهره‌وری آب بالا",
     "کاهش علف هرز",
     "کودآبیاری دقیق",
     "کم‌تنش‌تر بودن گیاه"
    ]
   },
   {
    "h": "اشتباهات رایج",
    "p": [
     "فیلتر ضعیف و گرفتگی قطره‌چکان، فشار نامناسب و نبود برنامه شست‌وشو — نگهداری حرف اول را می‌زند."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/irrigation",
   "tools/drip-design",
   "forum/irrigation",
   "blog/water-scarcity"
  ]
 },
 "learn/irrigation/scheduling": {
  "title": "مقاله: زمان‌بندی آبیاری",
  "description": "چه زمانی آبیاری کنیم؟",
  "badge": "آموزش",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "سنجش رطوبت خاک (سنسور یا وزنی)",
     "محاسبه بیلان آب (ETo − بارش)",
     "ظاهر گیاه (روش کم‌دقت)"
    ]
   },
   {
    "h": "اصل",
    "p": [
     "آبیاری زمانی که رطوبت به آستانه (مثلاً ۵۰٪ رطوبت قابل استفاده) رسید — نه زودتر و نه دیرتر."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/irrigation",
   "tools/soil-water",
   "tools/irrigation",
   "forum/water"
  ]
 },
 "learn/pests/ipm": {
  "title": "مقاله: مدیریت تلفیقی آفات",
  "description": "IPM — ترکیب هوشمند روش‌ها.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "سطوح",
    "p": [],
    "b": [
     "پیشگیری (تناوب، رقم مقاوم، بهداشت)",
     "پایش و آستانه اقتصادی",
     "کنترل مکانیکی و زیستی",
     "سم فقط در آستانه و با انتخاب هدفمند"
    ]
   }
  ],
  "related": [
   "learn/pests",
   "learn/pests/biocontrol",
   "learn/ecology",
   "forum/soil"
  ]
 },
 "learn/pests/biocontrol": {
  "title": "مقاله: کنترل زیستی",
  "description": "دشمنان طبیعی را به خدمت بگیرید.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "عوامل",
    "p": [],
    "b": [
     "زنبورهای پارازیتوئید",
     "کفشدوزک و بالتوری",
     "قارچ‌ها و باکتری‌های بیمارگر",
     "گیاهان جاذب"
    ]
   }
  ],
  "related": [
   "learn/pests",
   "learn/ecology",
   "forum/soil",
   "learn/pests/ipm"
  ]
 },
 "learn/ecology/biodiversity": {
  "title": "مقاله: تنوع زیستی مزرعه",
  "description": "مزرعه‌ای با تنوع بیشتر، پایدارتر.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "اقدامات",
    "p": [],
    "b": [
     "حاشیه گل‌دار برای گرده‌افشان",
     "پرچین و درختچه",
     "کاهش سموم پهن‌اثر",
     "ایجاد زیستگاه‌های کوچک"
    ]
   }
  ],
  "related": [
   "learn/ecology",
   "learn/pests/biocontrol",
   "blog/soil-health",
   "community"
  ]
 },
 "learn/agronomy/tillage": {
  "title": "مقاله: خاک‌ورزی حفاظتی",
  "description": "کم‌خاک‌ورزی و بی‌خاک‌ورزی.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "مزایا",
    "p": [],
    "b": [
     "حفظ بقایا روی سطح",
     "کاهش فرسایش",
     "افزایش ماده آلی",
     "صرفه‌جویی سوخت"
    ]
   },
   {
    "h": "چالش‌ها",
    "p": [
     "مدیریت بقایا و علف‌های هرز نیازمند دانش و ماشین مناسب است — تغییر تدریجی پیشنهاد می‌شود."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/agronomy",
   "learn/soil",
   "blog/soil-health",
   "tools/carbon-stock"
  ]
 },
 "learn/compost/cn-ratio": {
  "title": "مقاله: نسبت C/N کمپوست",
  "description": "کلید موفقیت کمپوست: کربن و نیتروژن متعادل.",
  "badge": "آموزش",
  "sections": [
   {
    "h": "چرا مهم است؟",
    "p": [
     "نسبت C/N بالای ۴۰ تجزیه را کُند می‌کند؛ پایین‌تر از ۲۰ نیتروژن به شکل آمونیاک تلف و بو ایجاد می‌شود.",
     "بازه بهینه: ۲۵ تا ۳۵. کاه (۸۰:۱) با کود دامی (۲۰:۱) حدود ۲ به ۱ ترکیب شود."
    ],
    "b": []
   }
  ],
  "related": [
   "learn/compost",
   "tools/compost-cn",
   "learn/soil/organic-matter",
   "forum/soil"
  ]
 },
 "modules/ai/overview": {
  "title": "دستیار هوشمند — نمای کلی",
  "description": "دستیار دانش‌بنیان: پرسش، بازیابی دانش و پاسخ مستند.",
  "badge": "ماژول هوش مصنوعی",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "پاسخ با استناد به دانشنامه FAO",
     "موتور بازیابی RAG",
     "اتصال به مدل محلی Ollama (اختیاری)",
     "۱۴ زبان"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه دستیار هوشمند — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/ecowallet/guide",
   "modules/ai/science",
   "modules/ai/faq"
  ]
 },
 "modules/ai/guide": {
  "title": "دستیار هوشمند — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول دستیار هوشمند.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "سؤال را به فارسی یا هر زبان پشتیبان بنویسید",
     "پاسخ همراه با منابع و درصد ارتباط می‌آید",
     "برای کیفیت بهتر، مدل محلی (مثلاً glm4:9b) را نصب کنید"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/overview",
   "modules/ai/science",
   "modules/ai/faq"
  ]
 },
 "modules/ai/science": {
  "title": "دستیار هوشمند — پایه علمی",
  "description": "مبانی علمی پشت ماژول دستیار هوشمند.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "بازیابی TF-IDF روی دانشنامه علمی",
     "سنتز پاسخ فقط از متن بازیابی‌شده — بدون اختراع",
     "در نبود مدل محلی، پاسخ خام با اخطار صادقانه"
    ]
   }
  ],
  "related": [
   "modules/ai/overview",
   "modules/ai/guide",
   "science/models"
  ]
 },
 "modules/ai/faq": {
  "title": "دستیار هوشمند — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول دستیار هوشمند.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "آیا پاسخ‌ها همیشه دقیق‌اند؟",
    "p": [
     "پاسخ‌ها بر پایه اسناد بازیابی‌شده ساخته می‌شوند و منبع هر پاسخ نمایش داده می‌شود؛ برای تصمیم‌های مهم با کارشناس مشورت کنید."
    ],
    "b": []
   },
   {
    "h": "بدون اینترنت کار می‌کند؟",
    "p": [
     "در تلگرام/ایتا بله؛ مدل محلی بدون نیاز به اینترنت پرسرعت پاسخ می‌دهد."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/overview",
   "modules/ai/guide",
   "faq"
  ]
 },
 "modules/analytics/overview": {
  "title": "تحلیل‌ها — نمای کلی",
  "description": "داشبوردهای تحلیلی آب، خاک و عملکرد.",
  "badge": "ماژول تحلیل",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "نمودارهای سری زمانی",
     "مقایسه مزرعه‌ها",
     "گزارش‌های آماری",
     "خروجی CSV"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه تحلیل‌ها — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/carbon/guide",
   "modules/ecowallet/guide",
   "modules/analytics/science",
   "modules/analytics/faq"
  ]
 },
 "modules/analytics/guide": {
  "title": "تحلیل‌ها — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول تحلیل‌ها.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "گزاره را انتخاب کنید",
     "بازه زمانی را تنظیم کنید",
     "نمودارها به‌صورت تعاملی‌اند"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/analytics/overview",
   "modules/analytics/science",
   "modules/analytics/faq"
  ]
 },
 "modules/analytics/science": {
  "title": "تحلیل‌ها — پایه علمی",
  "description": "مبانی علمی پشت ماژول تحلیل‌ها.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "آمار توصیفی و روند",
     "همبستگی متغیرهای خاک و آب"
    ]
   }
  ],
  "related": [
   "modules/analytics/overview",
   "modules/analytics/guide",
   "science/models"
  ]
 },
 "modules/analytics/faq": {
  "title": "تحلیل‌ها — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول تحلیل‌ها.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "داده از کجا می‌آید؟",
    "p": [
     "فعلاً از داده آزمایشی/شبیه‌سازی (W-001)؛ از فاز ۴ داده واقعی کوپرنیکوس می‌آید."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/analytics/overview",
   "modules/analytics/guide",
   "faq"
  ]
 },
 "modules/carbon/overview": {
  "title": "کربن — نمای کلی",
  "description": "برآورد کربن خاک، ترسیب و مسیر اعتبار کربن.",
  "badge": "ماژول کربن",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "محاسبه ذخیره کربن",
     "سناریوی ترسیب",
     "معادل CO₂",
     "گزارش"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه کربن — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/ecowallet/guide",
   "modules/carbon/science",
   "modules/carbon/faq"
  ]
 },
 "modules/carbon/guide": {
  "title": "کربن — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول کربن.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "مشخصات خاک (C%، جرم مخصوص، عمق) را وارد کنید",
     "نتیجه به تن بر هکتار و معادل CO₂ نمایش داده می‌شود"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/carbon/overview",
   "modules/carbon/science",
   "modules/carbon/faq"
  ]
 },
 "modules/carbon/science": {
  "title": "کربن — پایه علمی",
  "description": "مبانی علمی پشت ماژول کربن.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "روش IPCC Tier 1",
     "ضریب تبدیل ۳٫۶۷ برای CO₂",
     "روش‌شناسی هدف: VM0042 (پس از مجوز قانونی)"
    ]
   }
  ],
  "related": [
   "modules/carbon/overview",
   "modules/carbon/guide",
   "science/models"
  ]
 },
 "modules/carbon/faq": {
  "title": "کربن — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول کربن.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "آیا توکن کربن عرضه می‌شود؟",
    "p": [
     "خیر تا اخذ مجوز قانونی؛ تبلیغ رمزارز در ایران محدود است (بهمن ۱۴۰۳)."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/carbon/overview",
   "modules/carbon/guide",
   "faq"
  ]
 },
 "modules/ecowallet/overview": {
  "title": "کیف پول اکو — نمای کلی",
  "description": "امتیازها و تراکنش‌های اکو.",
  "badge": "ماژول اقتصاد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "موجودی اکو",
     "تاریخچه تراکنش",
     "پاداش یادگیری",
     "گزارش ماهانه"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه کیف پول اکو — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/ecowallet/science",
   "modules/ecowallet/faq"
  ]
 },
 "modules/ecowallet/guide": {
  "title": "کیف پول اکو — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول کیف پول اکو.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "با فعالیت (یادگیری، ثبت مزرعه، مشارکت) اکو بگیرید",
     "تاریخچه همه تراکنش‌ها شفاف است"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ecowallet/overview",
   "modules/ecowallet/science",
   "modules/ecowallet/faq"
  ]
 },
 "modules/ecowallet/science": {
  "title": "کیف پول اکو — پایه علمی",
  "description": "مبانی علمی پشت ماژول کیف پول اکو.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [
     "این ماژول عمدتاً تجربه‌کاربری و فرآیندی است؛ مدل‌های علمی مرتبط در فاز ۷ یکپارچه می‌شوند."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ecowallet/overview",
   "modules/ecowallet/guide",
   "science/models"
  ]
 },
 "modules/ecowallet/faq": {
  "title": "کیف پول اکو — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول کیف پول اکو.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "اکو پول واقعی است؟",
    "p": [
     "در حال حاضر امتیاز درون‌پلتفرمی است؛ تبدیل به ارزش اقتصادی پس از بررسی‌های قانونی (فاز ۸)."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ecowallet/overview",
   "modules/ecowallet/guide",
   "faq"
  ]
 },
 "modules/erosion/overview": {
  "title": "فرسایش — نمای کلی",
  "description": "برآورد فرسایش خاک و سناریوهای حفاظتی.",
  "badge": "ماژول خاک",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "RUSLE ساده‌شده",
     "مقایسه سناریوها",
     "نقشه خطر (آینده)",
     "توصیه حفاظتی"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه فرسایش — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/erosion/science",
   "modules/erosion/faq"
  ]
 },
 "modules/erosion/guide": {
  "title": "فرسایش — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول فرسایش.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "فاکتورهای R، K، LS، C، P را وارد کنید",
     "خروجی: تن فرسایش در هکتار در سال و سطح خطر"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/erosion/overview",
   "modules/erosion/science",
   "modules/erosion/faq"
  ]
 },
 "modules/erosion/science": {
  "title": "فرسایش — پایه علمی",
  "description": "مبانی علمی پشت ماژول فرسایش.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "معادله جهانی هدررفت خاک (RUSLE)",
     "آستانه قابل قبول ≈ ۱۰ تن در هکتار در سال"
    ]
   }
  ],
  "related": [
   "modules/erosion/overview",
   "modules/erosion/guide",
   "science/models"
  ]
 },
 "modules/erosion/faq": {
  "title": "فرسایش — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول فرسایش.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "دقت چقدر است؟",
    "p": [
     "برآورد آموزشی؛ مدل میدانی دقیق‌تر در فاز ۷ با کتابخانه ۲۲ مدل می‌آید."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/erosion/overview",
   "modules/erosion/guide",
   "faq"
  ]
 },
 "modules/marketplace/overview": {
  "title": "بازار — نمای کلی",
  "description": "بازار محصولات و نهاده‌های کشاورزی.",
  "badge": "ماژول بازار",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "ثبت آگهی",
     "جستجو و فیلتر",
     "چت مستقیم",
     "امتیاز اعتماد"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه بازار — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/marketplace/science",
   "modules/marketplace/faq"
  ]
 },
 "modules/marketplace/guide": {
  "title": "بازار — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول بازار.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "آگهی ثبت کنید یا جستجو کنید",
     "برای خرید/فروش مستقیم با طرف مقابل گفتگو کنید"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/marketplace/overview",
   "modules/marketplace/science",
   "modules/marketplace/faq"
  ]
 },
 "modules/marketplace/science": {
  "title": "بازار — پایه علمی",
  "description": "مبانی علمی پشت ماژول بازار.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [
     "این ماژول عمدتاً تجربه‌کاربری و فرآیندی است؛ مدل‌های علمی مرتبط در فاز ۷ یکپارچه می‌شوند."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/marketplace/overview",
   "modules/marketplace/guide",
   "science/models"
  ]
 },
 "modules/marketplace/faq": {
  "title": "بازار — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول بازار.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "هزینه‌ای دارد؟",
    "p": [
     "ثبت آگهی رایگان است؛ مدل درآمدی بعداً اعلام می‌شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/marketplace/overview",
   "modules/marketplace/guide",
   "faq"
  ]
 },
 "modules/satellite/overview": {
  "title": "ماهواره — نمای کلی",
  "description": "پایش ماهواره‌ای پوشش گیاهی و رطوبت.",
  "badge": "ماژول ماهواره",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "NDVI",
     "رطوبت خاک",
     "هشدار تنش",
     "سری زمانی"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه ماهواره — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/satellite/science",
   "modules/satellite/faq"
  ]
 },
 "modules/satellite/guide": {
  "title": "ماهواره — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول ماهواره.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "مزرعه را انتخاب کنید",
     "شاخص‌ها روی نقشه و نمودار نمایش داده می‌شوند"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/satellite/overview",
   "modules/satellite/science",
   "modules/satellite/faq"
  ]
 },
 "modules/satellite/science": {
  "title": "ماهواره — پایه علمی",
  "description": "مبانی علمی پشت ماژول ماهواره.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "شاخص‌های طیفی (NDVI و همخانواده)",
     "خط لوله کوپرنیکوس CDSE از فاز ۴",
     "داده فعلی شبیه‌سازی‌شده است (W-001)"
    ]
   }
  ],
  "related": [
   "modules/satellite/overview",
   "modules/satellite/guide",
   "science/models"
  ]
 },
 "modules/satellite/faq": {
  "title": "ماهواره — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول ماهواره.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "کی داده واقعی می‌شود؟",
    "p": [
     "فاز ۴: اتصال به سرویس داده کوپرنیکوس."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/satellite/overview",
   "modules/satellite/guide",
   "faq"
  ]
 },
 "modules/scenarios/overview": {
  "title": "سناریوها — نمای کلی",
  "description": "شبیه‌سازی سناریوهای اقلیمی و مدیریتی.",
  "badge": "ماژول شبیه‌سازی",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "سناریوی خشک‌سالی",
     "سناریوی آبیاری",
     "مقایسه نتایج",
     "گزارش"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه سناریوها — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/scenarios/science",
   "modules/scenarios/faq"
  ]
 },
 "modules/scenarios/guide": {
  "title": "سناریوها — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول سناریوها.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "پارامترهای مزرعه را وارد کنید",
     "سناریو را اجرا و نتایج را مقایسه کنید"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/scenarios/overview",
   "modules/scenarios/science",
   "modules/scenarios/faq"
  ]
 },
 "modules/scenarios/science": {
  "title": "سناریوها — پایه علمی",
  "description": "مبانی علمی پشت ماژول سناریوها.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "موتور HyDroMa: ریچاردز، سن‌ونان، FAO-56",
     "شبیه‌سازهای PINN سریع در فاز ۷"
    ]
   }
  ],
  "related": [
   "modules/scenarios/overview",
   "modules/scenarios/guide",
   "science/models"
  ]
 },
 "modules/scenarios/faq": {
  "title": "سناریوها — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول سناریوها.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "اجرا چقدر طول می‌کشد؟",
    "p": [
     "هسته C++20 و Numba اجرا را زیر چند ثانیه نگه می‌دارند."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/scenarios/overview",
   "modules/scenarios/guide",
   "faq"
  ]
 },
 "modules/soil/overview": {
  "title": "خاک — نمای کلی",
  "description": "تحلیل و مدیریت سلامت خاک.",
  "badge": "ماژول خاک",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "ثبت آزمون خاک",
     "توصیه کود",
     "پایش pH و شوری",
     "گزارش"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه خاک — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/soil/science",
   "modules/soil/faq"
  ]
 },
 "modules/soil/guide": {
  "title": "خاک — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول خاک.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "نتایج آزمون خاک را وارد کنید",
     "توصیه بر پایه اصول علمی نمایش داده می‌شود"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/soil/overview",
   "modules/soil/science",
   "modules/soil/faq"
  ]
 },
 "modules/soil/science": {
  "title": "خاک — پایه علمی",
  "description": "مبانی علمی پشت ماژول خاک.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "مدل‌های van Genuchten و رطوبت خاک",
     "منحنی‌های توصیه تغذیه"
    ]
   }
  ],
  "related": [
   "modules/soil/overview",
   "modules/soil/guide",
   "science/models"
  ]
 },
 "modules/soil/faq": {
  "title": "خاک — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول خاک.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "آیا جایگزین آزمایشگاه است؟",
    "p": [
     "خیر؛ تکمیل‌کننده است و همیشه توصیه به آزمون استاندارد می‌کند."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/soil/overview",
   "modules/soil/guide",
   "faq"
  ]
 },
 "modules/voice/overview": {
  "title": "صوتی — نمای کلی",
  "description": "دسترسی صوتی برای کشاورزانی که متن برایشان سخت است.",
  "badge": "ماژول صوتی",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "پرسش صوتی",
     "پاسخ صوتی",
     "پشتیبانی USSD/SMS (نقشه راه)"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه صوتی — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/voice/science",
   "modules/voice/faq"
  ]
 },
 "modules/voice/guide": {
  "title": "صوتی — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول صوتی.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "دکمه میکروفون را فشار دهید و بپرسید",
     "پاسخ به‌صورت صوتی و متنی می‌آید"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/voice/overview",
   "modules/voice/science",
   "modules/voice/faq"
  ]
 },
 "modules/voice/science": {
  "title": "صوتی — پایه علمی",
  "description": "مبانی علمی پشت ماژول صوتی.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "تبدیل گفتار به متن و برعکس",
     "برای زبان فارسی تنظیم شده است"
    ]
   }
  ],
  "related": [
   "modules/voice/overview",
   "modules/voice/guide",
   "science/models"
  ]
 },
 "modules/voice/faq": {
  "title": "صوتی — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول صوتی.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "در کانال‌های پیامکی هم هست؟",
    "p": [
     "در نقشه راه (فازهای بعدی) است."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/voice/overview",
   "modules/voice/guide",
   "faq"
  ]
 },
 "modules/watershed/overview": {
  "title": "آبخیز — نمای کلی",
  "description": "مدل‌سازی رواناب و مدیریت آبخیز.",
  "badge": "ماژول آبخیز",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "رواناب سطحی",
     "رسوب (SDR/برون)",
     "سناریوی مدیریتی",
     "نقشه"
    ]
   },
   {
    "h": "این ماژول برای چه کسی است؟",
    "p": [
     "کاربران فعال در حوزه آبخیز — کشاورزان، مشاوران و پژوهشگران."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/ai/guide",
   "modules/analytics/guide",
   "modules/carbon/guide",
   "modules/watershed/science",
   "modules/watershed/faq"
  ]
 },
 "modules/watershed/guide": {
  "title": "آبخیز — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول آبخیز.",
  "badge": "راهنما",
  "sections": [
   {
    "h": "مراحل استفاده",
    "p": [],
    "b": [
     "مشخصات آبخیز را وارد کنید",
     "رواناب و رسوب محاسبه و نمایش داده می‌شود"
    ]
   },
   {
    "h": "نکته",
    "p": [
     "خروجی این ماژول آموزشی است و برای تصمیم‌های مهم با کارشناس محلی بررسی شود."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/watershed/overview",
   "modules/watershed/science",
   "modules/watershed/faq"
  ]
 },
 "modules/watershed/science": {
  "title": "آبخیز — پایه علمی",
  "description": "مبانی علمی پشت ماژول آبخیز.",
  "badge": "علم",
  "sections": [
   {
    "h": "روش‌ها",
    "p": [],
    "b": [
     "سن‌ونان ۱D",
     "RUSLE + SDR + برون",
     "موزکینگام-کانژ (روندیابی سیل)"
    ]
   }
  ],
  "related": [
   "modules/watershed/overview",
   "modules/watershed/guide",
   "science/models"
  ]
 },
 "modules/watershed/faq": {
  "title": "آبخیز — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول آبخیز.",
  "badge": "پرسش",
  "sections": [
   {
    "h": "برای سیل‌بندها قابل استفاده است؟",
    "p": [
     "خروجی‌های اولیه بله؛ طراحی نهایی با مهندس آب صورت گیرد."
    ],
    "b": []
   }
  ],
  "related": [
   "modules/watershed/overview",
   "modules/watershed/guide",
   "faq"
  ]
 },
 "dashboard/farms": {
  "title": "مزرعه‌های من",
  "description": "فهرست مزرعه‌های ثبت‌شده و وضعیت هر کدام.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "فهرست مزرعه‌ها با مختصات و مساحت",
     "وضعیت پایش",
     "دسترسی سریع به جزئیات"
    ]
   }
  ],
  "related": [
   "dashboard/overview",
   "dashboard/farms/new",
   "dashboard/farm-detail",
   "dashboard/alerts"
  ]
 },
 "dashboard/farms/new": {
  "title": "ثبت مزرعه جدید",
  "description": "افزودن مزرعه از وب — همانند جریان ربات.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "فرم ثبت",
    "p": [],
    "b": [
     "نام و مساحت (هکتار)",
     "مختصات (یا انتخاب روی نقشه)",
     "نوع خاک (اختیاری)"
    ]
   }
  ],
  "related": [
   "dashboard/farms",
   "dashboard/farm-detail",
   "help"
  ]
 },
 "dashboard/farm-detail": {
  "title": "جزئیات مزرعه",
  "description": "نمای کامل یک مزرعه: تحلیل‌ها، هشدارها و گزارش‌ها.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "بخش‌ها",
    "p": [],
    "b": [
     "خلاصه وضعیت",
     "تحلیل‌های خاک و آب",
     "هشدارهای فعال",
     "گزارش‌ها"
    ]
   }
  ],
  "related": [
   "dashboard/farms",
   "dashboard/analytics",
   "dashboard/alerts",
   "dashboard/reports"
  ]
 },
 "dashboard/activities": {
  "title": "فعالیت‌ها",
  "description": "تاریخچه فعالیت‌های شما در پلتفرم.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "نمونه رویدادها",
    "p": [],
    "b": [
     "ثبت مزرعه",
     "پرسش از کارشناس",
     "تکمیل ماژول آموزشی",
     "ثبت آگهی"
    ]
   }
  ],
  "related": [
   "dashboard/overview",
   "dashboard/reports",
   "account/notifications"
  ]
 },
 "dashboard/alerts": {
  "title": "هشدارها",
  "description": "هشدارهای هوشمند مزرعه شما (موتور هشدار فاز ۲).",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "قواعد نمونه",
    "p": [],
    "b": [
     "رطوبت خاک زیر ۲۵٪ → بحرانی",
     "رطوبت بالای ۸۰٪ → هشدار",
     "pH خارج از بازه → هشدار"
    ]
   },
   {
    "h": "اصل",
    "p": [
     "هشدار فقط با داده واقعی صادر می‌شود؛ تا فاز ۴ این صفحه ساختار را نشان می‌دهد."
    ],
    "b": []
   }
  ],
  "related": [
   "dashboard/farm-detail",
   "services/monitoring",
   "learn/irrigation/scheduling"
  ]
 },
 "dashboard/analytics": {
  "title": "تحلیل‌های من",
  "description": "نمودارها و آمار مزرعه‌های شما.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "نمادها",
    "p": [],
    "b": [
     "روند رطوبت خاک",
     "مقایسه مزرعه‌ها",
     "توزیع pH"
    ]
   }
  ],
  "related": [
   "dashboard/farm-detail",
   "modules/analytics",
   "dashboard/reports"
  ]
 },
 "dashboard/reports": {
  "title": "گزارش‌ها",
  "description": "گزارش‌های قابل دانلود مزرعه.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "گزارش‌ها",
    "p": [],
    "b": [
     "گزارش خاک",
     "گزارش آبیاری",
     "گزارش کربن",
     "خروجی CSV/PDF (به‌زودی)"
    ]
   }
  ],
  "related": [
   "dashboard/analytics",
   "dashboard/farms",
   "admin/analytics"
  ]
 },
 "dashboard/schedule": {
  "title": "تقویم کشاورزی",
  "description": "یادآوری‌های فصل کاشت، آبیاری و کود.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "رویدادها",
    "p": [],
    "b": [
     "زمان کاشت",
     "نوبت‌های آبیاری",
     "کوددهی",
     "برداشت"
    ]
   }
  ],
  "related": [
   "dashboard/farms",
   "learn/irrigation/scheduling",
   "account/notifications"
  ]
 },
 "dashboard/messages": {
  "title": "پیام‌ها",
  "description": "پیام‌های پشتیبانی و بازار.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "صندوق",
    "p": [],
    "b": [
     "پیام‌های پشتیبانی",
     "گفتگوی بازار",
     "اعلان‌های سیستمی"
    ]
   }
  ],
  "related": [
   "dashboard/marketplace",
   "support",
   "account/notifications"
  ]
 },
 "dashboard/marketplace": {
  "title": "بازار من",
  "description": "آگهی‌ها و معاملات شما در بازار.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "آگهی‌های فعال",
     "درخواست‌های دریافتی",
     "تاریخچه معاملات"
    ]
   }
  ],
  "related": [
   "modules/marketplace",
   "dashboard/messages",
   "services/marketplace"
  ]
 },
 "dashboard/wallet": {
  "title": "کیف پول من",
  "description": "موجودی و تراکنش‌های اکو شما.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "موجودی فعلی",
     "تراکنش‌ها",
     "پاداش‌ها"
    ]
   }
  ],
  "related": [
   "modules/ecowallet",
   "account/billing",
   "dashboard/education"
  ]
 },
 "dashboard/education": {
  "title": "آموزش من",
  "description": "پیشرفت آموزشی و امتیازهای شما.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "ماژول‌های تکمیل‌شده",
     "امتیاز کل",
     "سطح فعلی"
    ]
   }
  ],
  "related": [
   "learn",
   "dashboard/wallet",
   "modules/ecowallet"
  ]
 },
 "dashboard/support": {
  "title": "پشتیبانی من",
  "description": "تیکت‌ها و درخواست‌های پشتیبانی.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "تیکت جدید",
     "پیگیری تیکت‌ها",
     "راهنما"
    ]
   }
  ],
  "related": [
   "support",
   "faq",
   "dashboard/messages"
  ]
 },
 "dashboard/settings": {
  "title": "تنظیمات داشبورد",
  "description": "تنظیمات اعلان و نمایش.",
  "badge": "داشبورد",
  "sections": [
   {
    "h": "موارد",
    "p": [],
    "b": [
     "زبان و جهت",
     "اعلان‌های ربات",
     "قالب نمایش"
    ]
   }
  ],
  "related": [
   "settings",
   "account/notifications",
   "account/security"
  ]
 },
 "admin": {
  "title": "پنل مدیریت",
  "description": "پیش‌نمایش ساختار پنل مدیریت — نسخه عملیاتی در فاز ۵.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "ماژول‌ها",
    "p": [],
    "b": [
     "مدیریت محتوا",
     "کاربران و نقش‌ها",
     "مزرعه‌ها",
     "مدل‌ها و داده",
     "هشدارها",
     "ترجمه‌ها",
     "امنیت و پشتیبان"
    ]
   },
   {
    "h": "توجه",
    "p": [
     "این صفحات ساختار و مستندات ماژول را نمایش می‌دهند؛ پنل واقعی با احراز هویت در فاز ۵ ساخته می‌شود."
    ],
    "b": []
   }
  ],
  "related": [
   "admin/content",
   "admin/users",
   "admin/farms",
   "admin/analytics"
  ]
 },
 "admin/content": {
  "title": "مدیریت محتوا",
  "description": "انتشار یک‌باره، سه کانال: سایت، RAG و ربات‌ها.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "جریان کار",
    "p": [],
    "b": [
     "نوشتن مطلب",
     "ترجمه هوشمند ۱۴ زبان (مدل محلی)",
     "انتشار هم‌زمان در سایت، دانشنامه و ربات"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/translations",
   "services/education",
   "learn"
  ]
 },
 "admin/users": {
  "title": "مدیریت کاربران",
  "description": "کاربران، نقش‌ها و دسترسی‌ها (کشاورز، تعاونی، NGO، مدیر).",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "نقش‌ها",
    "p": [],
    "b": [
     "کشاورز",
     "تعاونی",
     "سازمان مردم‌نهاد",
     "مدیر"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/roles",
   "admin/security",
   "account/security"
  ]
 },
 "admin/farms": {
  "title": "مدیریت مزرعه‌ها",
  "description": "نمای کلان مزرعه‌های ثبت‌شده.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "فهرست و جستجو",
     "وضعیت پایش",
     "گزارش"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/data",
   "dashboard/farms",
   "admin/analytics"
  ]
 },
 "admin/models": {
  "title": "مدیریت مدل‌ها",
  "description": "مدل‌های علمی، نسخه‌ها و وضعیت.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "فهرست مدل‌ها",
     "نسخه‌بندی",
     "کارت مدل",
     "اجرای آزمایشی"
    ]
   }
  ],
  "related": [
   "admin",
   "science/models",
   "admin/data",
   "science/research"
  ]
 },
 "admin/data": {
  "title": "مدیریت داده",
  "description": "مجموعه‌داده‌ها، کیفیت و انتشار.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "کاتالوگ داده",
     "برچسب منبع (واقعی/شبیه‌سازی)",
     "انتشار با DOI (فاز ۹)"
    ]
   }
  ],
  "related": [
   "admin",
   "science/datasets",
   "admin/models",
   "science/open-data"
  ]
 },
 "admin/alerts": {
  "title": "مدیریت هشدارها",
  "description": "قواعد هشدار و وضعیت ارسال.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "تعریف قاعده",
     "تاریخچه ارسال",
     "گزارش خطا"
    ]
   }
  ],
  "related": [
   "admin",
   "dashboard/alerts",
   "services/monitoring",
   "admin/users"
  ]
 },
 "admin/translations": {
  "title": "مدیریت ترجمه‌ها",
  "description": "هماهنگی ۱۴ زبان پلتفرم.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "وضعیت ترجمه هر زبان",
     "اصلاح دستی",
     "بازبینی ترجمه ماشینی"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/content",
   "services/education",
   "community"
  ]
 },
 "admin/analytics": {
  "title": "تحلیل پلتفرم",
  "description": "آمار استفاده و عملکرد.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "نمادها",
    "p": [],
    "b": [
     "کاربران فعال",
     "پرسش‌های رایج",
     "صفحات پربازدید",
     "سلامت سرویس"
    ]
   }
  ],
  "related": [
   "admin",
   "modules/analytics",
   "admin/content",
   "dashboard/analytics"
  ]
 },
 "admin/settings": {
  "title": "تنظیمات سامانه",
  "description": "پیکربندی بدون ویرایش فایل .env.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "نام و برندینگ",
     "مدل پیش‌فرض هوش مصنوعی",
     "کلیدهای سرویس"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/security",
   "admin/backup",
   "settings"
  ]
 },
 "admin/security": {
  "title": "امنیت",
  "description": "نظارت امنیتی و سیاست‌های دسترسی.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "گزارش رویدادها (audit log)",
     "نقش‌ها و دسترسی‌ها",
     "سیاست رمز عبور",
     "رمزنگاری پس‌کوانتومی (فاز ۱۰)"
    ]
   }
  ],
  "related": [
   "admin",
   "legal/security",
   "admin/backup",
   "admin/roles"
  ]
 },
 "admin/backup": {
  "title": "پشتیبان‌گیری",
  "description": "بکاپ خودکار و بازگردانی — از فاز ۰ فعال است.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "بکاپ دوره‌ای (scripts/backup.py)",
     "بازگردانی یک‌دستوری",
     "نگهداری نسخه‌ها",
     "بکاپ گیت (bundle)"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/security",
   "admin/logs",
   "roadmap"
  ]
 },
 "admin/logs": {
  "title": "گزارش خطاها",
  "description": "لاگ‌های سامانه و رویدادها.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "لاگ درخواست‌ها",
     "خطاهای سرویس",
     "جستجو و فیلتر"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/security",
   "admin/analytics",
   "support"
  ]
 },
 "admin/roles": {
  "title": "نقش‌ها و دسترسی‌ها",
  "description": "مدل دسترسی مبتنی بر نقش (RBAC).",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "نقش‌ها",
    "p": [],
    "b": [
     "کشاورز: مزرعه‌های خودش",
     "تعاونی: اعضای تعاونی",
     "NGO: گزارش‌های منطقه",
     "مدیر: همه"
    ]
   }
  ],
  "related": [
   "admin",
   "admin/users",
   "admin/security",
   "legal/privacy"
  ]
 },
 "admin/docs": {
  "title": "مستندات فنی",
  "description": "راهنمای توسعه‌دهندگان و مستندات داخلی.",
  "badge": "مدیریت",
  "sections": [
   {
    "h": "بخش‌ها",
    "p": [],
    "b": [
     "معماری",
     "راهنمای فازها",
     "مستندات API",
     "استانداردهای کد"
    ]
   }
  ],
  "related": [
   "admin",
   "services/api",
   "science/repositories",
   "science/research"
  ]
 },
 "account": {
  "title": "حساب کاربری من",
  "description": "مرکز مدیریت حساب، اعلان‌ها و اشتراک.",
  "badge": "حساب",
  "sections": [
   {
    "h": "بخش‌ها",
    "p": [],
    "b": [
     "نمایه و مشخصات",
     "تنظیمات",
     "اعلان‌ها",
     "امنیت"
    ]
   }
  ],
  "related": [
   "profile",
   "settings",
   "account/notifications",
   "account/security"
  ]
 },
 "account/notifications": {
  "title": "اعلان‌ها",
  "description": "مدیریت اعلان‌های ربات، ایمیل و پیامک.",
  "badge": "حساب",
  "sections": [
   {
    "h": "کانال‌ها",
    "p": [],
    "b": [
     "ربات تلگرام/ایتا",
     "ایمیل",
     "اعلان مرورگر (PWA)"
    ]
   }
  ],
  "related": [
   "account",
   "dashboard/alerts",
   "dashboard/settings",
   "support"
  ]
 },
 "account/security": {
  "title": "امنیت حساب",
  "description": "رمز عبور، ورود دومرحله‌ای و نشست‌ها.",
  "badge": "حساب",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "تغییر رمز عبور",
     "ورود دومرحله‌ای (به‌زودی)",
     "مدیریت نشست‌ها"
    ]
   }
  ],
  "related": [
   "account",
   "account/devices",
   "admin/security",
   "legal/security"
  ]
 },
 "account/devices": {
  "title": "دستگاه‌ها",
  "description": "دستگاه‌هایی که با حساب شما وارد شده‌اند.",
  "badge": "حساب",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "فهرست نشست‌ها",
     "خروج از راه دور"
    ]
   }
  ],
  "related": [
   "account",
   "account/security",
   "account/notifications"
  ]
 },
 "account/subscriptions": {
  "title": "اشتراک‌ها",
  "description": "اشتراک‌های فعال و تاریخچه.",
  "badge": "حساب",
  "sections": [
   {
    "h": "وضعیت",
    "p": [],
    "b": [
     "اشتراک رایگان پایه",
     "خدمات ویژه (برنامه)"
    ]
   }
  ],
  "related": [
   "account",
   "account/billing",
   "pricing",
   "services"
  ]
 },
 "account/questions": {
  "title": "پرسش‌های من",
  "description": "تاریخچه پرسش‌های شما از کارشناس.",
  "badge": "حساب",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "تاریخچه پرسش‌ها",
     "پاسخ‌ها با منبع",
     "پرسش دوباره"
    ]
   }
  ],
  "related": [
   "account",
   "learn",
   "modules/ai",
   "dashboard/activities"
  ]
 },
 "account/saved": {
  "title": "نشان‌شده‌ها",
  "description": "مطالب و ابزارهایی که ذخیره کرده‌اید.",
  "badge": "حساب",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "مقالات نشان‌شده",
     "ماشین‌حساب‌های پرکاربرد"
    ]
   }
  ],
  "related": [
   "account",
   "learn",
   "blog",
   "tools"
  ]
 },
 "account/billing": {
  "title": "صورتحساب",
  "description": "سوابق مالی و فاکتورها.",
  "badge": "حساب",
  "sections": [
   {
    "h": "امکانات",
    "p": [],
    "b": [
     "فاکتورها",
     "روش‌های پرداخت",
     "تاریخچه"
    ]
   }
  ],
  "related": [
   "account",
   "account/subscriptions",
   "dashboard/wallet",
   "pricing"
  ]
 }
};
export const pagePaths: string[] = [
 "account",
 "account/billing",
 "account/devices",
 "account/notifications",
 "account/questions",
 "account/saved",
 "account/security",
 "account/subscriptions",
 "admin",
 "admin/alerts",
 "admin/analytics",
 "admin/backup",
 "admin/content",
 "admin/data",
 "admin/docs",
 "admin/farms",
 "admin/logs",
 "admin/models",
 "admin/roles",
 "admin/security",
 "admin/settings",
 "admin/translations",
 "admin/users",
 "blog",
 "blog/carbon-farming",
 "blog/climate-adaptation",
 "blog/soil-health",
 "blog/water-scarcity",
 "careers",
 "community",
 "community/guidelines",
 "dashboard/activities",
 "dashboard/alerts",
 "dashboard/analytics",
 "dashboard/education",
 "dashboard/farm-detail",
 "dashboard/farms",
 "dashboard/farms/new",
 "dashboard/marketplace",
 "dashboard/messages",
 "dashboard/reports",
 "dashboard/schedule",
 "dashboard/settings",
 "dashboard/support",
 "dashboard/wallet",
 "events",
 "faq",
 "forum",
 "forum/carbon",
 "forum/irrigation",
 "forum/soil",
 "forum/water",
 "help",
 "learn/agronomy",
 "learn/agronomy/tillage",
 "learn/carbon",
 "learn/carbon/accounting",
 "learn/carbon/sequestration",
 "learn/climate",
 "learn/climate/adaptation",
 "learn/climate/greenhouse",
 "learn/compost",
 "learn/compost/cn-ratio",
 "learn/crops",
 "learn/crops/nutrition",
 "learn/crops/rotation",
 "learn/ecology",
 "learn/ecology/biodiversity",
 "learn/irrigation",
 "learn/irrigation/drip",
 "learn/irrigation/scheduling",
 "learn/pests",
 "learn/pests/biocontrol",
 "learn/pests/ipm",
 "learn/soil",
 "learn/soil/organic-matter",
 "learn/soil/ph",
 "learn/soil/salinity",
 "learn/soil/texture",
 "learn/water",
 "learn/water/footprint",
 "learn/water/management",
 "learn/water/quality",
 "modules/ai/faq",
 "modules/ai/guide",
 "modules/ai/overview",
 "modules/ai/science",
 "modules/analytics/faq",
 "modules/analytics/guide",
 "modules/analytics/overview",
 "modules/analytics/science",
 "modules/carbon/faq",
 "modules/carbon/guide",
 "modules/carbon/overview",
 "modules/carbon/science",
 "modules/ecowallet/faq",
 "modules/ecowallet/guide",
 "modules/ecowallet/overview",
 "modules/ecowallet/science",
 "modules/erosion/faq",
 "modules/erosion/guide",
 "modules/erosion/overview",
 "modules/erosion/science",
 "modules/marketplace/faq",
 "modules/marketplace/guide",
 "modules/marketplace/overview",
 "modules/marketplace/science",
 "modules/satellite/faq",
 "modules/satellite/guide",
 "modules/satellite/overview",
 "modules/satellite/science",
 "modules/scenarios/faq",
 "modules/scenarios/guide",
 "modules/scenarios/overview",
 "modules/scenarios/science",
 "modules/soil/faq",
 "modules/soil/guide",
 "modules/soil/overview",
 "modules/soil/science",
 "modules/voice/faq",
 "modules/voice/guide",
 "modules/voice/overview",
 "modules/voice/science",
 "modules/watershed/faq",
 "modules/watershed/guide",
 "modules/watershed/overview",
 "modules/watershed/science",
 "news",
 "news/launch",
 "news/partnership",
 "newsletter",
 "partners",
 "press",
 "roadmap",
 "science",
 "science/citations",
 "science/datasets",
 "science/field-pilot",
 "science/labs",
 "science/models",
 "science/open-data",
 "science/publications",
 "science/repositories",
 "science/research",
 "services",
 "services/advisory",
 "services/api",
 "services/carbon",
 "services/consulting",
 "services/education",
 "services/marketplace",
 "services/monitoring",
 "services/training",
 "services/wallet",
 "support",
 "webinars"
];
