// AUTO-GENERATED by scripts/generate_pages.py (Phase 3) — do not edit by hand.
export interface SiteEntry { path: string; title: string; description: string; group: string; }
export const siteRegistry: Record<string, SiteEntry> = {
 "services": {
  "path": "services",
  "title": "خدمات اکو نوژین",
  "description": "مجموعه کامل خدمات دانش‌بنیان برای کشاورزی اقلیم‌هوشمند، آب، خاک و کربن — از مشاوره تا بازار.",
  "group": "services"
 },
 "services/advisory": {
  "path": "services/advisory",
  "title": "خدمت مشاوره علمی",
  "description": "دستیار دانش‌بنیان کشاورزی: سؤال بپرسید، پاسخ مستند بگیرید.",
  "group": "services"
 },
 "services/monitoring": {
  "path": "services/monitoring",
  "title": "خدمت پایش مزرعه",
  "description": "پایش ماهواره‌ای پوشش گیاهی، رطوبت و تنش — با داده واقعی از فاز ۴.",
  "group": "services"
 },
 "services/carbon": {
  "path": "services/carbon",
  "title": "خدمت کربن و اقلیم",
  "description": "مسیر ترسیب کربن خاک و گزارش‌دهی اقلیمی برای کشاورزی.",
  "group": "services"
 },
 "services/education": {
  "path": "services/education",
  "title": "خدمت آموزش",
  "description": "یادگیری گام‌به‌گام با امتیاز و سطح‌بندی — دانش علمی در قالب تجربه.",
  "group": "services"
 },
 "services/marketplace": {
  "path": "services/marketplace",
  "title": "خدمت بازار کشاورزان",
  "description": "بازار محصولات و نهاده‌ها — کشاورز به کشاورز.",
  "group": "services"
 },
 "services/wallet": {
  "path": "services/wallet",
  "title": "کیف پول اکو",
  "description": "مدیریت امتیازها و تراکنش‌های اکو در اکوسیستم پلتفرم.",
  "group": "services"
 },
 "services/api": {
  "path": "services/api",
  "title": "API برای توسعه‌دهندگان",
  "description": "دسترسی برنامه‌نویسی به موتور مدل‌سازی و دانش اکو نوژین.",
  "group": "services"
 },
 "services/consulting": {
  "path": "services/consulting",
  "title": "مشاوره تخصصی",
  "description": "اتصال کشاورز به کارشناسان و مراکز ترویج.",
  "group": "services"
 },
 "services/training": {
  "path": "services/training",
  "title": "دوره‌های آموزشی",
  "description": "دوره‌های کوتاه علمی برای کشاورزان و دانشجویان.",
  "group": "services"
 },
 "partners": {
  "path": "partners",
  "title": "همکاران",
  "description": "همکاری با دانشگاه‌ها، مراکز ترویج و سازمان‌های زیست‌محیطی.",
  "group": "info"
 },
 "roadmap": {
  "path": "roadmap",
  "title": "نقشه راه",
  "description": "برنامه ۱۱ فازی اکو نوژین — از پایه امنیت تا مقیاس و عملیات میدانی.",
  "group": "info"
 },
 "careers": {
  "path": "careers",
  "title": "همکاری با ما",
  "description": "اکو نوژین با کار تیمی بدون نیروی فنی تمام‌وقت ساخته می‌شود — مشارکت موضوعی و میدانی بپذیریم.",
  "group": "info"
 },
 "press": {
  "path": "press",
  "title": "رسانه",
  "description": "اخبار، بیانیه‌ها و معرفی پلتفرم برای رسانه‌ها.",
  "group": "info"
 },
 "newsletter": {
  "path": "newsletter",
  "title": "خبرنامه",
  "description": "خلاصه هفتگی اخبار علمی و به‌روزرسانی‌های پلتفرم.",
  "group": "info"
 },
 "events": {
  "path": "events",
  "title": "رویدادها",
  "description": "کارگاه‌ها و رویدادهای حضوری و آنلاین.",
  "group": "info"
 },
 "webinars": {
  "path": "webinars",
  "title": "وبینارها",
  "description": "جلسات آنلاین آموزشی با کارشناسان.",
  "group": "info"
 },
 "blog": {
  "path": "blog",
  "title": "وبلاگ",
  "description": "نوشته‌های علمی-کاربردی درباره خاک، آب، اقلیم و کشاورزی.",
  "group": "info"
 },
 "blog/soil-health": {
  "path": "blog/soil-health",
  "title": "سلامت خاک: چرا مهم است؟",
  "description": "خاک سالم، غذای سالم — مرور شاخص‌های کلیدی سلامت خاک.",
  "group": "info"
 },
 "blog/water-scarcity": {
  "path": "blog/water-scarcity",
  "title": "بحران آب و کشاورزی",
  "description": "چگونه با مدیریت صحیح آبیاری، بحران آب را مهار کنیم؟",
  "group": "info"
 },
 "blog/carbon-farming": {
  "path": "blog/carbon-farming",
  "title": "کشاورزی کربنی",
  "description": "ترسیب کربن در خاک به‌عنوان راهکار اقلیمی و درآمد نو.",
  "group": "info"
 },
 "blog/climate-adaptation": {
  "path": "blog/climate-adaptation",
  "title": "سازگاری با تغییر اقلیم",
  "description": "اقدامات عملی برای مزرعه‌ای مقاوم در برابر اقلیم متغیر.",
  "group": "info"
 },
 "news": {
  "path": "news",
  "title": "اخبار",
  "description": "به‌روزرسانی‌ها و دستاوردهای پلتفرم اکو نوژین.",
  "group": "info"
 },
 "news/launch": {
  "path": "news/launch",
  "title": "رونمایی فاز ۳",
  "description": "فرانت‌اند کاربر با بیش از ۱۵۰ صفحه فعال رونمایی شد.",
  "group": "info"
 },
 "news/partnership": {
  "path": "news/partnership",
  "title": "همکاری دانشگاهی",
  "description": "برنامه پایلوت میدانی با دانشگاه‌ها — سه روستا (فاز ۱۰).",
  "group": "info"
 },
 "faq": {
  "path": "faq",
  "title": "پرسش‌های پرتکرار",
  "description": "پاسخ به پرسش‌های رایج درباره پلتفرم.",
  "group": "support"
 },
 "help": {
  "path": "help",
  "title": "راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از سرویس‌ها.",
  "group": "support"
 },
 "support": {
  "path": "support",
  "title": "پشتیبانی",
  "description": "مسیرهای ارتباط با تیم پشتیبانی.",
  "group": "support"
 },
 "community": {
  "path": "community",
  "title": "جامعه کاربران",
  "description": "فضای تبادل تجربه کشاورزان، دانشجویان و کارشناسان.",
  "group": "community"
 },
 "community/guidelines": {
  "path": "community/guidelines",
  "title": "قوانین جامعه",
  "description": "چارچوب رفتاری برای گفتگوی سالم در انجمن‌ها.",
  "group": "community"
 },
 "forum": {
  "path": "forum",
  "title": "انجمن گفتگو",
  "description": "پرسش و پاسخ کاربران درباره خاک، آب، آفات و مدیریت مزرعه.",
  "group": "community"
 },
 "forum/soil": {
  "path": "forum/soil",
  "title": "انجمن خاک",
  "description": "بحث درباره سلامت خاک، کود و اصلاح خاک.",
  "group": "community"
 },
 "forum/water": {
  "path": "forum/water",
  "title": "انجمن آب",
  "description": "مدیریت آب کشاورزی و آبیاری.",
  "group": "community"
 },
 "forum/carbon": {
  "path": "forum/carbon",
  "title": "انجمن کربن",
  "description": "ترسیب کربن، کمپوست و اقتصاد سبز.",
  "group": "community"
 },
 "forum/irrigation": {
  "path": "forum/irrigation",
  "title": "انجمن آبیاری",
  "description": "طراحی و نگهداری سامانه‌های آبیاری.",
  "group": "community"
 },
 "science": {
  "path": "science",
  "title": "مرکز علم",
  "description": "پنجره باز علم: مدل‌ها، داده‌ها، انتشارات و بازتولیدپذیری.",
  "group": "science"
 },
 "science/research": {
  "path": "science/research",
  "title": "پژوهش",
  "description": "پروژه‌های پژوهشی پلتفرم و مسیر همکاری علمی.",
  "group": "science"
 },
 "science/datasets": {
  "path": "science/datasets",
  "title": "مجموعه‌داده‌ها",
  "description": "کاتالوگ داده‌های باز پلتفرم.",
  "group": "science"
 },
 "science/models": {
  "path": "science/models",
  "title": "کتابخانه مدل‌ها",
  "description": "مدل‌های علمی قابل اجرا — از ریچاردز تا یادگیری ماشین.",
  "group": "science"
 },
 "science/publications": {
  "path": "science/publications",
  "title": "انتشارات",
  "description": "مقالات و گزارش‌های علمی پلتفرم.",
  "group": "science"
 },
 "science/citations": {
  "path": "science/citations",
  "title": "استناد خودکار",
  "description": "پاسخ‌های هوشمند با ارجاع خودکار به OpenAlex، FAO و Crossref (فاز ۹).",
  "group": "science"
 },
 "science/open-data": {
  "path": "science/open-data",
  "title": "داده‌باز",
  "description": "تعهد به داده‌باز و علم باز.",
  "group": "science"
 },
 "science/repositories": {
  "path": "science/repositories",
  "title": "مخزن کد و داده",
  "description": "مخزن‌های عمومی پروژه.",
  "group": "science"
 },
 "science/labs": {
  "path": "science/labs",
  "title": "همکاری آزمایشگاهی",
  "description": "آزمایشگاه‌های خاک و آب شریک.",
  "group": "science"
 },
 "science/field-pilot": {
  "path": "science/field-pilot",
  "title": "پایلوت میدانی",
  "description": "برنامه سه‌روستا با دانشگاه‌ها — اعتبارسنجی در مزرعه واقعی (فاز ۱۰).",
  "group": "science"
 },
 "learn/soil": {
  "path": "learn/soil",
  "title": "آموزش: خاک",
  "description": "مفاهیم پایه خاک — بافت، pH، ماده آلی، شوری و سلامت خاک.",
  "group": "learn"
 },
 "learn/water": {
  "path": "learn/water",
  "title": "آموزش: آب",
  "description": "مدیریت آب کشاورزی — نیاز آبی، کیفیت و بهره‌وری.",
  "group": "learn"
 },
 "learn/climate": {
  "path": "learn/climate",
  "title": "آموزش: اقلیم",
  "description": "تغییر اقلیم، پیش‌بینی و سازگاری در مزرعه.",
  "group": "learn"
 },
 "learn/carbon": {
  "path": "learn/carbon",
  "title": "آموزش: کربن",
  "description": "چرخه کربن، ترسیب در خاک و گزارش‌دهی.",
  "group": "learn"
 },
 "learn/crops": {
  "path": "learn/crops",
  "title": "آموزش: گیاهان زراعی",
  "description": "تغذیه گیاه، تناوب و انتخاب رقم.",
  "group": "learn"
 },
 "learn/irrigation": {
  "path": "learn/irrigation",
  "title": "آموزش: آبیاری",
  "description": "روش‌ها و زمان‌بندی آبیاری مدرن.",
  "group": "learn"
 },
 "learn/pests": {
  "path": "learn/pests",
  "title": "آموزش: آفات",
  "description": "مدیریت تلفیقی آفات (IPM) و کنترل زیستی.",
  "group": "learn"
 },
 "learn/ecology": {
  "path": "learn/ecology",
  "title": "آموزش: بوم‌شناسی",
  "description": "تنوع زیستی و خدمات اکوسیستم در مزرعه.",
  "group": "learn"
 },
 "learn/agronomy": {
  "path": "learn/agronomy",
  "title": "آموزش: زراعت",
  "description": "مدیریت زراعی — خاک‌ورزی، کاشت و داشت.",
  "group": "learn"
 },
 "learn/compost": {
  "path": "learn/compost",
  "title": "آموزش: کمپوست",
  "description": "تولید کمپوست با کیفیت — از مواد اولیه تا محصول نهایی.",
  "group": "learn"
 },
 "learn/soil/ph": {
  "path": "learn/soil/ph",
  "title": "مقاله: pH خاک",
  "description": "چرا pH خاک مهم است و چگونه آن را اصلاح کنیم؟",
  "group": "learn"
 },
 "learn/soil/organic-matter": {
  "path": "learn/soil/organic-matter",
  "title": "مقاله: ماده آلی خاک",
  "description": "ماده آلی — قلب سلامت خاک.",
  "group": "learn"
 },
 "learn/soil/salinity": {
  "path": "learn/soil/salinity",
  "title": "مقاله: شوری خاک",
  "description": "شناخت و مدیریت خاک‌های شور.",
  "group": "learn"
 },
 "learn/soil/texture": {
  "path": "learn/soil/texture",
  "title": "مقاله: بافت خاک",
  "description": "شن، سیلت و رس — چرا بافت مهم است؟",
  "group": "learn"
 },
 "learn/water/quality": {
  "path": "learn/water/quality",
  "title": "مقاله: کیفیت آب آبیاری",
  "description": "EC، SAR و عناصر خطرناک در آب آبیاری.",
  "group": "learn"
 },
 "learn/water/management": {
  "path": "learn/water/management",
  "title": "مقاله: مدیریت آب مزرعه",
  "description": "برنامه‌ریزی آبیاری در شرایط کم‌آبی.",
  "group": "learn"
 },
 "learn/water/footprint": {
  "path": "learn/water/footprint",
  "title": "مقاله: ردپای آب",
  "description": "هر محصول چقدر آب مصرف می‌کند؟",
  "group": "learn"
 },
 "learn/climate/greenhouse": {
  "path": "learn/climate/greenhouse",
  "title": "مقاله: گازهای گلخانه‌ای در کشاورزی",
  "description": "سهم کشاورزی از انتشار و راه‌های کاهش.",
  "group": "learn"
 },
 "learn/climate/adaptation": {
  "path": "learn/climate/adaptation",
  "title": "مقاله: سازگاری مزرعه با اقلیم",
  "description": "آماده‌سازی مزرعه برای اقلیم متغیر.",
  "group": "learn"
 },
 "learn/carbon/sequestration": {
  "path": "learn/carbon/sequestration",
  "title": "مقاله: ترسیب کربن در خاک",
  "description": "خاک‌ها چگونه کربن ذخیره می‌کنند؟",
  "group": "learn"
 },
 "learn/carbon/accounting": {
  "path": "learn/carbon/accounting",
  "title": "مقاله: حسابداری کربن",
  "description": "اندازه‌گیری و گزارش کربن مزرعه.",
  "group": "learn"
 },
 "learn/crops/rotation": {
  "path": "learn/crops/rotation",
  "title": "مقاله: تناوب زراعی",
  "description": "چرا تناوب، زراعت را نجات می‌دهد؟",
  "group": "learn"
 },
 "learn/crops/nutrition": {
  "path": "learn/crops/nutrition",
  "title": "مقاله: تغذیه گیاه",
  "description": "عناصر پرمصرف و کم‌مصرف — زمان و روش مصرف.",
  "group": "learn"
 },
 "learn/irrigation/drip": {
  "path": "learn/irrigation/drip",
  "title": "مقاله: آبیاری قطره‌ای",
  "description": "مزایا، اجزا و اشتباهات رایج.",
  "group": "learn"
 },
 "learn/irrigation/scheduling": {
  "path": "learn/irrigation/scheduling",
  "title": "مقاله: زمان‌بندی آبیاری",
  "description": "چه زمانی آبیاری کنیم؟",
  "group": "learn"
 },
 "learn/pests/ipm": {
  "path": "learn/pests/ipm",
  "title": "مقاله: مدیریت تلفیقی آفات",
  "description": "IPM — ترکیب هوشمند روش‌ها.",
  "group": "learn"
 },
 "learn/pests/biocontrol": {
  "path": "learn/pests/biocontrol",
  "title": "مقاله: کنترل زیستی",
  "description": "دشمنان طبیعی را به خدمت بگیرید.",
  "group": "learn"
 },
 "learn/ecology/biodiversity": {
  "path": "learn/ecology/biodiversity",
  "title": "مقاله: تنوع زیستی مزرعه",
  "description": "مزرعه‌ای با تنوع بیشتر، پایدارتر.",
  "group": "learn"
 },
 "learn/agronomy/tillage": {
  "path": "learn/agronomy/tillage",
  "title": "مقاله: خاک‌ورزی حفاظتی",
  "description": "کم‌خاک‌ورزی و بی‌خاک‌ورزی.",
  "group": "learn"
 },
 "learn/compost/cn-ratio": {
  "path": "learn/compost/cn-ratio",
  "title": "مقاله: نسبت C/N کمپوست",
  "description": "کلید موفقیت کمپوست: کربن و نیتروژن متعادل.",
  "group": "learn"
 },
 "modules/ai/overview": {
  "path": "modules/ai/overview",
  "title": "دستیار هوشمند — نمای کلی",
  "description": "دستیار دانش‌بنیان: پرسش، بازیابی دانش و پاسخ مستند.",
  "group": "modules"
 },
 "modules/ai/guide": {
  "path": "modules/ai/guide",
  "title": "دستیار هوشمند — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول دستیار هوشمند.",
  "group": "modules"
 },
 "modules/ai/science": {
  "path": "modules/ai/science",
  "title": "دستیار هوشمند — پایه علمی",
  "description": "مبانی علمی پشت ماژول دستیار هوشمند.",
  "group": "modules"
 },
 "modules/ai/faq": {
  "path": "modules/ai/faq",
  "title": "دستیار هوشمند — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول دستیار هوشمند.",
  "group": "modules"
 },
 "modules/analytics/overview": {
  "path": "modules/analytics/overview",
  "title": "تحلیل‌ها — نمای کلی",
  "description": "داشبوردهای تحلیلی آب، خاک و عملکرد.",
  "group": "modules"
 },
 "modules/analytics/guide": {
  "path": "modules/analytics/guide",
  "title": "تحلیل‌ها — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول تحلیل‌ها.",
  "group": "modules"
 },
 "modules/analytics/science": {
  "path": "modules/analytics/science",
  "title": "تحلیل‌ها — پایه علمی",
  "description": "مبانی علمی پشت ماژول تحلیل‌ها.",
  "group": "modules"
 },
 "modules/analytics/faq": {
  "path": "modules/analytics/faq",
  "title": "تحلیل‌ها — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول تحلیل‌ها.",
  "group": "modules"
 },
 "modules/carbon/overview": {
  "path": "modules/carbon/overview",
  "title": "کربن — نمای کلی",
  "description": "برآورد کربن خاک، ترسیب و مسیر اعتبار کربن.",
  "group": "modules"
 },
 "modules/carbon/guide": {
  "path": "modules/carbon/guide",
  "title": "کربن — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول کربن.",
  "group": "modules"
 },
 "modules/carbon/science": {
  "path": "modules/carbon/science",
  "title": "کربن — پایه علمی",
  "description": "مبانی علمی پشت ماژول کربن.",
  "group": "modules"
 },
 "modules/carbon/faq": {
  "path": "modules/carbon/faq",
  "title": "کربن — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول کربن.",
  "group": "modules"
 },
 "modules/ecowallet/overview": {
  "path": "modules/ecowallet/overview",
  "title": "کیف پول اکو — نمای کلی",
  "description": "امتیازها و تراکنش‌های اکو.",
  "group": "modules"
 },
 "modules/ecowallet/guide": {
  "path": "modules/ecowallet/guide",
  "title": "کیف پول اکو — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول کیف پول اکو.",
  "group": "modules"
 },
 "modules/ecowallet/science": {
  "path": "modules/ecowallet/science",
  "title": "کیف پول اکو — پایه علمی",
  "description": "مبانی علمی پشت ماژول کیف پول اکو.",
  "group": "modules"
 },
 "modules/ecowallet/faq": {
  "path": "modules/ecowallet/faq",
  "title": "کیف پول اکو — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول کیف پول اکو.",
  "group": "modules"
 },
 "modules/erosion/overview": {
  "path": "modules/erosion/overview",
  "title": "فرسایش — نمای کلی",
  "description": "برآورد فرسایش خاک و سناریوهای حفاظتی.",
  "group": "modules"
 },
 "modules/erosion/guide": {
  "path": "modules/erosion/guide",
  "title": "فرسایش — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول فرسایش.",
  "group": "modules"
 },
 "modules/erosion/science": {
  "path": "modules/erosion/science",
  "title": "فرسایش — پایه علمی",
  "description": "مبانی علمی پشت ماژول فرسایش.",
  "group": "modules"
 },
 "modules/erosion/faq": {
  "path": "modules/erosion/faq",
  "title": "فرسایش — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول فرسایش.",
  "group": "modules"
 },
 "modules/marketplace/overview": {
  "path": "modules/marketplace/overview",
  "title": "بازار — نمای کلی",
  "description": "بازار محصولات و نهاده‌های کشاورزی.",
  "group": "modules"
 },
 "modules/marketplace/guide": {
  "path": "modules/marketplace/guide",
  "title": "بازار — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول بازار.",
  "group": "modules"
 },
 "modules/marketplace/science": {
  "path": "modules/marketplace/science",
  "title": "بازار — پایه علمی",
  "description": "مبانی علمی پشت ماژول بازار.",
  "group": "modules"
 },
 "modules/marketplace/faq": {
  "path": "modules/marketplace/faq",
  "title": "بازار — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول بازار.",
  "group": "modules"
 },
 "modules/satellite/overview": {
  "path": "modules/satellite/overview",
  "title": "ماهواره — نمای کلی",
  "description": "پایش ماهواره‌ای پوشش گیاهی و رطوبت.",
  "group": "modules"
 },
 "modules/satellite/guide": {
  "path": "modules/satellite/guide",
  "title": "ماهواره — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول ماهواره.",
  "group": "modules"
 },
 "modules/satellite/science": {
  "path": "modules/satellite/science",
  "title": "ماهواره — پایه علمی",
  "description": "مبانی علمی پشت ماژول ماهواره.",
  "group": "modules"
 },
 "modules/satellite/faq": {
  "path": "modules/satellite/faq",
  "title": "ماهواره — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول ماهواره.",
  "group": "modules"
 },
 "modules/scenarios/overview": {
  "path": "modules/scenarios/overview",
  "title": "سناریوها — نمای کلی",
  "description": "شبیه‌سازی سناریوهای اقلیمی و مدیریتی.",
  "group": "modules"
 },
 "modules/scenarios/guide": {
  "path": "modules/scenarios/guide",
  "title": "سناریوها — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول سناریوها.",
  "group": "modules"
 },
 "modules/scenarios/science": {
  "path": "modules/scenarios/science",
  "title": "سناریوها — پایه علمی",
  "description": "مبانی علمی پشت ماژول سناریوها.",
  "group": "modules"
 },
 "modules/scenarios/faq": {
  "path": "modules/scenarios/faq",
  "title": "سناریوها — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول سناریوها.",
  "group": "modules"
 },
 "modules/soil/overview": {
  "path": "modules/soil/overview",
  "title": "خاک — نمای کلی",
  "description": "تحلیل و مدیریت سلامت خاک.",
  "group": "modules"
 },
 "modules/soil/guide": {
  "path": "modules/soil/guide",
  "title": "خاک — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول خاک.",
  "group": "modules"
 },
 "modules/soil/science": {
  "path": "modules/soil/science",
  "title": "خاک — پایه علمی",
  "description": "مبانی علمی پشت ماژول خاک.",
  "group": "modules"
 },
 "modules/soil/faq": {
  "path": "modules/soil/faq",
  "title": "خاک — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول خاک.",
  "group": "modules"
 },
 "modules/voice/overview": {
  "path": "modules/voice/overview",
  "title": "صوتی — نمای کلی",
  "description": "دسترسی صوتی برای کشاورزانی که متن برایشان سخت است.",
  "group": "modules"
 },
 "modules/voice/guide": {
  "path": "modules/voice/guide",
  "title": "صوتی — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول صوتی.",
  "group": "modules"
 },
 "modules/voice/science": {
  "path": "modules/voice/science",
  "title": "صوتی — پایه علمی",
  "description": "مبانی علمی پشت ماژول صوتی.",
  "group": "modules"
 },
 "modules/voice/faq": {
  "path": "modules/voice/faq",
  "title": "صوتی — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول صوتی.",
  "group": "modules"
 },
 "modules/watershed/overview": {
  "path": "modules/watershed/overview",
  "title": "آبخیز — نمای کلی",
  "description": "مدل‌سازی رواناب و مدیریت آبخیز.",
  "group": "modules"
 },
 "modules/watershed/guide": {
  "path": "modules/watershed/guide",
  "title": "آبخیز — راهنما",
  "description": "راهنمای گام‌به‌گام استفاده از ماژول آبخیز.",
  "group": "modules"
 },
 "modules/watershed/science": {
  "path": "modules/watershed/science",
  "title": "آبخیز — پایه علمی",
  "description": "مبانی علمی پشت ماژول آبخیز.",
  "group": "modules"
 },
 "modules/watershed/faq": {
  "path": "modules/watershed/faq",
  "title": "آبخیز — پرسش‌ها",
  "description": "پاسخ به پرسش‌های پرتکرار ماژول آبخیز.",
  "group": "modules"
 },
 "dashboard/farms": {
  "path": "dashboard/farms",
  "title": "مزرعه‌های من",
  "description": "فهرست مزرعه‌های ثبت‌شده و وضعیت هر کدام.",
  "group": "dashboard"
 },
 "dashboard/farms/new": {
  "path": "dashboard/farms/new",
  "title": "ثبت مزرعه جدید",
  "description": "افزودن مزرعه از وب — همانند جریان ربات.",
  "group": "dashboard"
 },
 "dashboard/farm-detail": {
  "path": "dashboard/farm-detail",
  "title": "جزئیات مزرعه",
  "description": "نمای کامل یک مزرعه: تحلیل‌ها، هشدارها و گزارش‌ها.",
  "group": "dashboard"
 },
 "dashboard/activities": {
  "path": "dashboard/activities",
  "title": "فعالیت‌ها",
  "description": "تاریخچه فعالیت‌های شما در پلتفرم.",
  "group": "dashboard"
 },
 "dashboard/alerts": {
  "path": "dashboard/alerts",
  "title": "هشدارها",
  "description": "هشدارهای هوشمند مزرعه شما (موتور هشدار فاز ۲).",
  "group": "dashboard"
 },
 "dashboard/analytics": {
  "path": "dashboard/analytics",
  "title": "تحلیل‌های من",
  "description": "نمودارها و آمار مزرعه‌های شما.",
  "group": "dashboard"
 },
 "dashboard/reports": {
  "path": "dashboard/reports",
  "title": "گزارش‌ها",
  "description": "گزارش‌های قابل دانلود مزرعه.",
  "group": "dashboard"
 },
 "dashboard/schedule": {
  "path": "dashboard/schedule",
  "title": "تقویم کشاورزی",
  "description": "یادآوری‌های فصل کاشت، آبیاری و کود.",
  "group": "dashboard"
 },
 "dashboard/messages": {
  "path": "dashboard/messages",
  "title": "پیام‌ها",
  "description": "پیام‌های پشتیبانی و بازار.",
  "group": "dashboard"
 },
 "dashboard/marketplace": {
  "path": "dashboard/marketplace",
  "title": "بازار من",
  "description": "آگهی‌ها و معاملات شما در بازار.",
  "group": "dashboard"
 },
 "dashboard/wallet": {
  "path": "dashboard/wallet",
  "title": "کیف پول من",
  "description": "موجودی و تراکنش‌های اکو شما.",
  "group": "dashboard"
 },
 "dashboard/education": {
  "path": "dashboard/education",
  "title": "آموزش من",
  "description": "پیشرفت آموزشی و امتیازهای شما.",
  "group": "dashboard"
 },
 "dashboard/support": {
  "path": "dashboard/support",
  "title": "پشتیبانی من",
  "description": "تیکت‌ها و درخواست‌های پشتیبانی.",
  "group": "dashboard"
 },
 "dashboard/settings": {
  "path": "dashboard/settings",
  "title": "تنظیمات داشبورد",
  "description": "تنظیمات اعلان و نمایش.",
  "group": "dashboard"
 },
 "admin": {
  "path": "admin",
  "title": "پنل مدیریت",
  "description": "پیش‌نمایش ساختار پنل مدیریت — نسخه عملیاتی در فاز ۵.",
  "group": "admin"
 },
 "admin/content": {
  "path": "admin/content",
  "title": "مدیریت محتوا",
  "description": "انتشار یک‌باره، سه کانال: سایت، RAG و ربات‌ها.",
  "group": "admin"
 },
 "admin/users": {
  "path": "admin/users",
  "title": "مدیریت کاربران",
  "description": "کاربران، نقش‌ها و دسترسی‌ها (کشاورز، تعاونی، NGO، مدیر).",
  "group": "admin"
 },
 "admin/farms": {
  "path": "admin/farms",
  "title": "مدیریت مزرعه‌ها",
  "description": "نمای کلان مزرعه‌های ثبت‌شده.",
  "group": "admin"
 },
 "admin/models": {
  "path": "admin/models",
  "title": "مدیریت مدل‌ها",
  "description": "مدل‌های علمی، نسخه‌ها و وضعیت.",
  "group": "admin"
 },
 "admin/data": {
  "path": "admin/data",
  "title": "مدیریت داده",
  "description": "مجموعه‌داده‌ها، کیفیت و انتشار.",
  "group": "admin"
 },
 "admin/alerts": {
  "path": "admin/alerts",
  "title": "مدیریت هشدارها",
  "description": "قواعد هشدار و وضعیت ارسال.",
  "group": "admin"
 },
 "admin/translations": {
  "path": "admin/translations",
  "title": "مدیریت ترجمه‌ها",
  "description": "هماهنگی ۱۴ زبان پلتفرم.",
  "group": "admin"
 },
 "admin/analytics": {
  "path": "admin/analytics",
  "title": "تحلیل پلتفرم",
  "description": "آمار استفاده و عملکرد.",
  "group": "admin"
 },
 "admin/settings": {
  "path": "admin/settings",
  "title": "تنظیمات سامانه",
  "description": "پیکربندی بدون ویرایش فایل .env.",
  "group": "admin"
 },
 "admin/security": {
  "path": "admin/security",
  "title": "امنیت",
  "description": "نظارت امنیتی و سیاست‌های دسترسی.",
  "group": "admin"
 },
 "admin/backup": {
  "path": "admin/backup",
  "title": "پشتیبان‌گیری",
  "description": "بکاپ خودکار و بازگردانی — از فاز ۰ فعال است.",
  "group": "admin"
 },
 "admin/logs": {
  "path": "admin/logs",
  "title": "گزارش خطاها",
  "description": "لاگ‌های سامانه و رویدادها.",
  "group": "admin"
 },
 "admin/roles": {
  "path": "admin/roles",
  "title": "نقش‌ها و دسترسی‌ها",
  "description": "مدل دسترسی مبتنی بر نقش (RBAC).",
  "group": "admin"
 },
 "admin/docs": {
  "path": "admin/docs",
  "title": "مستندات فنی",
  "description": "راهنمای توسعه‌دهندگان و مستندات داخلی.",
  "group": "admin"
 },
 "account": {
  "path": "account",
  "title": "حساب کاربری من",
  "description": "مرکز مدیریت حساب، اعلان‌ها و اشتراک.",
  "group": "account"
 },
 "account/notifications": {
  "path": "account/notifications",
  "title": "اعلان‌ها",
  "description": "مدیریت اعلان‌های ربات، ایمیل و پیامک.",
  "group": "account"
 },
 "account/security": {
  "path": "account/security",
  "title": "امنیت حساب",
  "description": "رمز عبور، ورود دومرحله‌ای و نشست‌ها.",
  "group": "account"
 },
 "account/devices": {
  "path": "account/devices",
  "title": "دستگاه‌ها",
  "description": "دستگاه‌هایی که با حساب شما وارد شده‌اند.",
  "group": "account"
 },
 "account/subscriptions": {
  "path": "account/subscriptions",
  "title": "اشتراک‌ها",
  "description": "اشتراک‌های فعال و تاریخچه.",
  "group": "account"
 },
 "account/questions": {
  "path": "account/questions",
  "title": "پرسش‌های من",
  "description": "تاریخچه پرسش‌های شما از کارشناس.",
  "group": "account"
 },
 "account/saved": {
  "path": "account/saved",
  "title": "نشان‌شده‌ها",
  "description": "مطالب و ابزارهایی که ذخیره کرده‌اید.",
  "group": "account"
 },
 "account/billing": {
  "path": "account/billing",
  "title": "صورتحساب",
  "description": "سوابق مالی و فاکتورها.",
  "group": "account"
 },
 "tools/irrigation": {
  "path": "tools/irrigation",
  "title": "ماشین‌حساب: نیاز آبیاری گیاه",
  "description": "برآورد نیاز آبی با روش FAO-56 ساده‌شده (Kc × ETo).",
  "group": "tools"
 },
 "tools/compost-cn": {
  "path": "tools/compost-cn",
  "title": "ماشین‌حساب: نسبت C/N کمپوست",
  "description": "محاسبه نسبت کربن به نیتروژن مخلوط کاه و کود دامی.",
  "group": "tools"
 },
 "tools/fertilizer": {
  "path": "tools/fertilizer",
  "title": "ماشین‌حساب: نیاز کود نیتروژنه",
  "description": "برآورد کود موردنیاز بر پایه نیاز گیاه و نیتروژن خاک.",
  "group": "tools"
 },
 "tools/carbon-stock": {
  "path": "tools/carbon-stock",
  "title": "ماشین‌حساب: ذخیره کربن خاک",
  "description": "محاسبه کربن آلی خاک و معادل CO₂ (روش IPCC).",
  "group": "tools"
 },
 "tools/erosion": {
  "path": "tools/erosion",
  "title": "ماشین‌حساب: فرسایش خاک (RUSLE)",
  "description": "برآورد فرسایش سالانه با معادله جهانی هدررفت خاک.",
  "group": "tools"
 },
 "tools/water-footprint": {
  "path": "tools/water-footprint",
  "title": "ماشین‌حساب: ردپای آب محصول",
  "description": "حجم آب مصرفی به ازای هر تن محصول.",
  "group": "tools"
 },
 "tools/seeding": {
  "path": "tools/seeding",
  "title": "ماشین‌حساب: میزان بذر",
  "description": "محاسبه بذر موردنیاز بر پایه تراکم و جوانه‌زنی.",
  "group": "tools"
 },
 "tools/lime": {
  "path": "tools/lime",
  "title": "ماشین‌حساب: نیاز آهک",
  "description": "برآورد آهک برای رساندن pH به بازه مطلوب.",
  "group": "tools"
 },
 "tools/soil-water": {
  "path": "tools/soil-water",
  "title": "ماشین‌حساب: کمبود رطوبت خاک",
  "description": "اختلاف رطوبت فعلی با ظرفیت مزرعه در عمق ریشه.",
  "group": "tools"
 },
 "tools/drip-design": {
  "path": "tools/drip-design",
  "title": "ماشین‌حساب: طراحی قطره‌ای",
  "description": "تعداد قطره‌چکان و دبی کل (ساده‌شده).",
  "group": "tools"
 },
 "tools/biomass": {
  "path": "tools/biomass",
  "title": "ماشین‌حساب: زیست‌توده خشک",
  "description": "تبدیل وزن تر به خشک با درصد رطوبت.",
  "group": "tools"
 },
 "tools/co2-offset": {
  "path": "tools/co2-offset",
  "title": "ماشین‌حساب: معادل CO₂",
  "description": "تبدیل کربن به دی‌اکسیدکربن معادل (×3.67).",
  "group": "tools"
 },
 "tools": {
  "path": "tools",
  "title": "ابزارها و ماشین‌حساب‌ها",
  "description": "ابزارهای محاسباتی تخصصی کشاورزی.",
  "group": "tools"
 },
 "pages": {
  "path": "pages",
  "title": "فهرست همه صفحات",
  "description": "دسترسی به همه ۱۵۰+ صفحه فعال پلتفرم.",
  "group": "info"
 }
};
export const SITE_GROUPS: { key: string; title: string }[] = [
 {
  "key": "services",
  "title": "خدمات"
 },
 {
  "key": "info",
  "title": "سازمان، اخبار و وبلاگ"
 },
 {
  "key": "support",
  "title": "پشتیبانی"
 },
 {
  "key": "community",
  "title": "جامعه"
 },
 {
  "key": "science",
  "title": "مرکز علم"
 },
 {
  "key": "learn",
  "title": "آموزش"
 },
 {
  "key": "tools",
  "title": "ابزار و ماشین‌حساب‌ها"
 },
 {
  "key": "modules",
  "title": "ماژول‌ها"
 },
 {
  "key": "dashboard",
  "title": "داشبورد"
 },
 {
  "key": "admin",
  "title": "مدیریت"
 },
 {
  "key": "account",
  "title": "حساب کاربری"
 }
];
