apiVersion: v1
kind: Namespace
metadata:
  name: eco-nojin
  labels:
    name: eco-nojin
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
  labels:
    name: tracing
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    name: velero